// Code generated by mockery. DO NOT EDIT.

package payment

import (
	context "context"
	payment "parkieee/internal/modules/payment"
	"time"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryPort is an autogenerated mock type for the RepositoryPort type
type MockRepositoryPort struct {
	mock.Mock
}

type MockRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryPort) EXPECT() *MockRepositoryPort_Expecter {
	return &MockRepositoryPort_Expecter{mock: &_m.Mock}
}

// CreatePayment provides a mock function with given fields: ctx, p
func (_m *MockRepositoryPort) CreatePayment(ctx context.Context, p *payment.Payment) error {
	ret := _m.Called(ctx, p)
	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockRepositoryPort_Expecter) CreatePayment(ctx interface{}, p interface{}) *mock.Call {
	return _e.mock.On("CreatePayment", ctx, p)
}

// CreateRefund provides a mock function with given fields: ctx, r
func (_m *MockRepositoryPort) CreateRefund(ctx context.Context, r *payment.Refund) error {
	ret := _m.Called(ctx, r)
	if len(ret) == 0 {
		panic("no return value specified for CreateRefund")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.Refund) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockRepositoryPort_Expecter) CreateRefund(ctx interface{}, r interface{}) *mock.Call {
	return _e.mock.On("CreateRefund", ctx, r)
}

// FindPaymentByID provides a mock function with given fields: ctx, id
func (_m *MockRepositoryPort) FindPaymentByID(ctx context.Context, id uuid.UUID) (*payment.Payment, error) {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for FindPaymentByID")
	}
	var r0 *payment.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*payment.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *payment.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Payment)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockRepositoryPort_Expecter) FindPaymentByID(ctx interface{}, id interface{}) *mock.Call {
	return _e.mock.On("FindPaymentByID", ctx, id)
}

// FindPaymentByMidtransOrderID provides a mock function with given fields: ctx, orderID
func (_m *MockRepositoryPort) FindPaymentByMidtransOrderID(ctx context.Context, orderID string) (*payment.Payment, error) {
	ret := _m.Called(ctx, orderID)
	if len(ret) == 0 {
		panic("no return value specified for FindPaymentByMidtransOrderID")
	}
	var r0 *payment.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*payment.Payment, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *payment.Payment); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Payment)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockRepositoryPort_Expecter) FindPaymentByMidtransOrderID(ctx interface{}, orderID interface{}) *mock.Call {
	return _e.mock.On("FindPaymentByMidtransOrderID", ctx, orderID)
}

// FindPaymentsByTransactionID provides a mock function with given fields: ctx, txID
func (_m *MockRepositoryPort) FindPaymentsByTransactionID(ctx context.Context, txID uuid.UUID) ([]payment.Payment, error) {
	ret := _m.Called(ctx, txID)
	if len(ret) == 0 {
		panic("no return value specified for FindPaymentsByTransactionID")
	}
	var r0 []payment.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]payment.Payment, error)); ok {
		return rf(ctx, txID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []payment.Payment); ok {
		r0 = rf(ctx, txID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.Payment)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, txID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockRepositoryPort_Expecter) FindPaymentsByTransactionID(ctx interface{}, txID interface{}) *mock.Call {
	return _e.mock.On("FindPaymentsByTransactionID", ctx, txID)
}

// FindRefundByID provides a mock function with given fields: ctx, id
func (_m *MockRepositoryPort) FindRefundByID(ctx context.Context, id uuid.UUID) (*payment.Refund, error) {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for FindRefundByID")
	}
	var r0 *payment.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*payment.Refund, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *payment.Refund); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Refund)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockRepositoryPort_Expecter) FindRefundByID(ctx interface{}, id interface{}) *mock.Call {
	return _e.mock.On("FindRefundByID", ctx, id)
}

// FindRefundByPaymentID provides a mock function with given fields: ctx, paymentID
func (_m *MockRepositoryPort) FindRefundByPaymentID(ctx context.Context, paymentID uuid.UUID) ([]payment.Refund, error) {
	ret := _m.Called(ctx, paymentID)
	if len(ret) == 0 {
		panic("no return value specified for FindRefundByPaymentID")
	}
	var r0 []payment.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]payment.Refund, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []payment.Refund); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.Refund)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockRepositoryPort_Expecter) FindRefundByPaymentID(ctx interface{}, paymentID interface{}) *mock.Call {
	return _e.mock.On("FindRefundByPaymentID", ctx, paymentID)
}

// ListRefunds provides a mock function with given fields: ctx, page, pageSize
func (_m *MockRepositoryPort) ListRefunds(ctx context.Context, page int, pageSize int) ([]payment.Refund, int64, error) {
	ret := _m.Called(ctx, page, pageSize)
	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}
	var r0 []payment.Refund
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]payment.Refund, int64, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []payment.Refund); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.Refund)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

func (_e *MockRepositoryPort_Expecter) ListRefunds(ctx interface{}, page interface{}, pageSize interface{}) *mock.Call {
	return _e.mock.On("ListRefunds", ctx, page, pageSize)
}

// LogCallback provides a mock function with given fields: ctx, cb
func (_m *MockRepositoryPort) LogCallback(ctx context.Context, cb *payment.MidtransCallback) error {
	ret := _m.Called(ctx, cb)
	if len(ret) == 0 {
		panic("no return value specified for LogCallback")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.MidtransCallback) error); ok {
		r0 = rf(ctx, cb)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockRepositoryPort_Expecter) LogCallback(ctx interface{}, cb interface{}) *mock.Call {
	return _e.mock.On("LogCallback", ctx, cb)
}

// UpdateCallback provides a mock function with given fields: ctx, cb
func (_m *MockRepositoryPort) UpdateCallback(ctx context.Context, cb *payment.MidtransCallback) error {
	ret := _m.Called(ctx, cb)
	if len(ret) == 0 {
		panic("no return value specified for UpdateCallback")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.MidtransCallback) error); ok {
		r0 = rf(ctx, cb)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockRepositoryPort_Expecter) UpdateCallback(ctx interface{}, cb interface{}) *mock.Call {
	return _e.mock.On("UpdateCallback", ctx, cb)
}

// UpdatePayment provides a mock function with given fields: ctx, p
func (_m *MockRepositoryPort) UpdatePayment(ctx context.Context, p *payment.Payment) error {
	ret := _m.Called(ctx, p)
	if len(ret) == 0 {
		panic("no return value specified for UpdatePayment")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockRepositoryPort_Expecter) UpdatePayment(ctx interface{}, p interface{}) *mock.Call {
	return _e.mock.On("UpdatePayment", ctx, p)
}

// UpdateRefund provides a mock function with given fields: ctx, r
func (_m *MockRepositoryPort) UpdateRefund(ctx context.Context, r *payment.Refund) error {
	ret := _m.Called(ctx, r)
	if len(ret) == 0 {
		panic("no return value specified for UpdateRefund")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.Refund) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockRepositoryPort_Expecter) UpdateRefund(ctx interface{}, r interface{}) *mock.Call {
	return _e.mock.On("UpdateRefund", ctx, r)
}

// StampCashierRequested provides a mock function with given fields: ctx, txID, at
func (_m *MockRepositoryPort) StampCashierRequested(ctx context.Context, txID uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, txID, at)
	if len(ret) == 0 {
		panic("no return value specified for StampCashierRequested")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, txID, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockRepositoryPort_Expecter) StampCashierRequested(ctx interface{}, txID interface{}, at interface{}) *mock.Call {
	return _e.mock.On("StampCashierRequested", ctx, txID, at)
}

// FindPendingCashierRequests provides a mock function with given fields: ctx, since
func (_m *MockRepositoryPort) FindPendingCashierRequests(ctx context.Context, since string) ([]payment.PendingCashierRequest, error) {
	ret := _m.Called(ctx, since)
	if len(ret) == 0 {
		panic("no return value specified for FindPendingCashierRequests")
	}
	var r0 []payment.PendingCashierRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]payment.PendingCashierRequest, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []payment.PendingCashierRequest); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.PendingCashierRequest)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockRepositoryPort_Expecter) FindPendingCashierRequests(ctx interface{}, since interface{}) *mock.Call {
	return _e.mock.On("FindPendingCashierRequests", ctx, since)
}

// NewMockRepositoryPort creates a new instance of MockRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryPort {
	mock := &MockRepositoryPort{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
