// Code generated by mockery. DO NOT EDIT.

package payment

import (
	context "context"
	payment "parkieee/internal/modules/payment"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryPort is an autogenerated mock type for the RepositoryPort type
type MockRepositoryPort struct {
	mock.Mock
}

type MockRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryPort) EXPECT() *MockRepositoryPort_Expecter {
	return &MockRepositoryPort_Expecter{mock: &_m.Mock}
}

// CreatePayment provides a mock function with given fields: ctx, p
func (_m *MockRepositoryPort) CreatePayment(ctx context.Context, p *payment.Payment) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryPort_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type MockRepositoryPort_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - p *payment.Payment
func (_e *MockRepositoryPort_Expecter) CreatePayment(ctx interface{}, p interface{}) *MockRepositoryPort_CreatePayment_Call {
	return &MockRepositoryPort_CreatePayment_Call{Call: _e.mock.On("CreatePayment", ctx, p)}
}

func (_c *MockRepositoryPort_CreatePayment_Call) Run(run func(ctx context.Context, p *payment.Payment)) *MockRepositoryPort_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*payment.Payment))
	})
	return _c
}

func (_c *MockRepositoryPort_CreatePayment_Call) Return(_a0 error) *MockRepositoryPort_CreatePayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryPort_CreatePayment_Call) RunAndReturn(run func(context.Context, *payment.Payment) error) *MockRepositoryPort_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRefund provides a mock function with given fields: ctx, r
func (_m *MockRepositoryPort) CreateRefund(ctx context.Context, r *payment.Refund) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefund")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.Refund) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryPort_CreateRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefund'
type MockRepositoryPort_CreateRefund_Call struct {
	*mock.Call
}

// CreateRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - r *payment.Refund
func (_e *MockRepositoryPort_Expecter) CreateRefund(ctx interface{}, r interface{}) *MockRepositoryPort_CreateRefund_Call {
	return &MockRepositoryPort_CreateRefund_Call{Call: _e.mock.On("CreateRefund", ctx, r)}
}

func (_c *MockRepositoryPort_CreateRefund_Call) Run(run func(ctx context.Context, r *payment.Refund)) *MockRepositoryPort_CreateRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*payment.Refund))
	})
	return _c
}

func (_c *MockRepositoryPort_CreateRefund_Call) Return(_a0 error) *MockRepositoryPort_CreateRefund_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryPort_CreateRefund_Call) RunAndReturn(run func(context.Context, *payment.Refund) error) *MockRepositoryPort_CreateRefund_Call {
	_c.Call.Return(run)
	return _c
}

// FindPaymentByID provides a mock function with given fields: ctx, id
func (_m *MockRepositoryPort) FindPaymentByID(ctx context.Context, id uuid.UUID) (*payment.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindPaymentByID")
	}

	var r0 *payment.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*payment.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *payment.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryPort_FindPaymentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPaymentByID'
type MockRepositoryPort_FindPaymentByID_Call struct {
	*mock.Call
}

// FindPaymentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepositoryPort_Expecter) FindPaymentByID(ctx interface{}, id interface{}) *MockRepositoryPort_FindPaymentByID_Call {
	return &MockRepositoryPort_FindPaymentByID_Call{Call: _e.mock.On("FindPaymentByID", ctx, id)}
}

func (_c *MockRepositoryPort_FindPaymentByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepositoryPort_FindPaymentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryPort_FindPaymentByID_Call) Return(_a0 *payment.Payment, _a1 error) *MockRepositoryPort_FindPaymentByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryPort_FindPaymentByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*payment.Payment, error)) *MockRepositoryPort_FindPaymentByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPaymentByMidtransOrderID provides a mock function with given fields: ctx, orderID
func (_m *MockRepositoryPort) FindPaymentByMidtransOrderID(ctx context.Context, orderID string) (*payment.Payment, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindPaymentByMidtransOrderID")
	}

	var r0 *payment.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*payment.Payment, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *payment.Payment); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryPort_FindPaymentByMidtransOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPaymentByMidtransOrderID'
type MockRepositoryPort_FindPaymentByMidtransOrderID_Call struct {
	*mock.Call
}

// FindPaymentByMidtransOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockRepositoryPort_Expecter) FindPaymentByMidtransOrderID(ctx interface{}, orderID interface{}) *MockRepositoryPort_FindPaymentByMidtransOrderID_Call {
	return &MockRepositoryPort_FindPaymentByMidtransOrderID_Call{Call: _e.mock.On("FindPaymentByMidtransOrderID", ctx, orderID)}
}

func (_c *MockRepositoryPort_FindPaymentByMidtransOrderID_Call) Run(run func(ctx context.Context, orderID string)) *MockRepositoryPort_FindPaymentByMidtransOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryPort_FindPaymentByMidtransOrderID_Call) Return(_a0 *payment.Payment, _a1 error) *MockRepositoryPort_FindPaymentByMidtransOrderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryPort_FindPaymentByMidtransOrderID_Call) RunAndReturn(run func(context.Context, string) (*payment.Payment, error)) *MockRepositoryPort_FindPaymentByMidtransOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPaymentsByTransactionID provides a mock function with given fields: ctx, txID
func (_m *MockRepositoryPort) FindPaymentsByTransactionID(ctx context.Context, txID uuid.UUID) ([]payment.Payment, error) {
	ret := _m.Called(ctx, txID)

	if len(ret) == 0 {
		panic("no return value specified for FindPaymentsByTransactionID")
	}

	var r0 []payment.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]payment.Payment, error)); ok {
		return rf(ctx, txID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []payment.Payment); ok {
		r0 = rf(ctx, txID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, txID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryPort_FindPaymentsByTransactionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPaymentsByTransactionID'
type MockRepositoryPort_FindPaymentsByTransactionID_Call struct {
	*mock.Call
}

// FindPaymentsByTransactionID is a helper method to define mock.On call
//   - ctx context.Context
//   - txID uuid.UUID
func (_e *MockRepositoryPort_Expecter) FindPaymentsByTransactionID(ctx interface{}, txID interface{}) *MockRepositoryPort_FindPaymentsByTransactionID_Call {
	return &MockRepositoryPort_FindPaymentsByTransactionID_Call{Call: _e.mock.On("FindPaymentsByTransactionID", ctx, txID)}
}

func (_c *MockRepositoryPort_FindPaymentsByTransactionID_Call) Run(run func(ctx context.Context, txID uuid.UUID)) *MockRepositoryPort_FindPaymentsByTransactionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryPort_FindPaymentsByTransactionID_Call) Return(_a0 []payment.Payment, _a1 error) *MockRepositoryPort_FindPaymentsByTransactionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryPort_FindPaymentsByTransactionID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]payment.Payment, error)) *MockRepositoryPort_FindPaymentsByTransactionID_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefundByID provides a mock function with given fields: ctx, id
func (_m *MockRepositoryPort) FindRefundByID(ctx context.Context, id uuid.UUID) (*payment.Refund, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindRefundByID")
	}

	var r0 *payment.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*payment.Refund, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *payment.Refund); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Refund)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryPort_FindRefundByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefundByID'
type MockRepositoryPort_FindRefundByID_Call struct {
	*mock.Call
}

// FindRefundByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepositoryPort_Expecter) FindRefundByID(ctx interface{}, id interface{}) *MockRepositoryPort_FindRefundByID_Call {
	return &MockRepositoryPort_FindRefundByID_Call{Call: _e.mock.On("FindRefundByID", ctx, id)}
}

func (_c *MockRepositoryPort_FindRefundByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepositoryPort_FindRefundByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryPort_FindRefundByID_Call) Return(_a0 *payment.Refund, _a1 error) *MockRepositoryPort_FindRefundByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryPort_FindRefundByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*payment.Refund, error)) *MockRepositoryPort_FindRefundByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefundByPaymentID provides a mock function with given fields: ctx, paymentID
func (_m *MockRepositoryPort) FindRefundByPaymentID(ctx context.Context, paymentID uuid.UUID) ([]payment.Refund, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for FindRefundByPaymentID")
	}

	var r0 []payment.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]payment.Refund, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []payment.Refund); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.Refund)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryPort_FindRefundByPaymentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefundByPaymentID'
type MockRepositoryPort_FindRefundByPaymentID_Call struct {
	*mock.Call
}

// FindRefundByPaymentID is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID uuid.UUID
func (_e *MockRepositoryPort_Expecter) FindRefundByPaymentID(ctx interface{}, paymentID interface{}) *MockRepositoryPort_FindRefundByPaymentID_Call {
	return &MockRepositoryPort_FindRefundByPaymentID_Call{Call: _e.mock.On("FindRefundByPaymentID", ctx, paymentID)}
}

func (_c *MockRepositoryPort_FindRefundByPaymentID_Call) Run(run func(ctx context.Context, paymentID uuid.UUID)) *MockRepositoryPort_FindRefundByPaymentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryPort_FindRefundByPaymentID_Call) Return(_a0 []payment.Refund, _a1 error) *MockRepositoryPort_FindRefundByPaymentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryPort_FindRefundByPaymentID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]payment.Refund, error)) *MockRepositoryPort_FindRefundByPaymentID_Call {
	_c.Call.Return(run)
	return _c
}

// ListRefunds provides a mock function with given fields: ctx, page, pageSize
func (_m *MockRepositoryPort) ListRefunds(ctx context.Context, page int, pageSize int) ([]payment.Refund, int64, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}

	var r0 []payment.Refund
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]payment.Refund, int64, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []payment.Refund); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.Refund)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepositoryPort_ListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefunds'
type MockRepositoryPort_ListRefunds_Call struct {
	*mock.Call
}

// ListRefunds is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockRepositoryPort_Expecter) ListRefunds(ctx interface{}, page interface{}, pageSize interface{}) *MockRepositoryPort_ListRefunds_Call {
	return &MockRepositoryPort_ListRefunds_Call{Call: _e.mock.On("ListRefunds", ctx, page, pageSize)}
}

func (_c *MockRepositoryPort_ListRefunds_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockRepositoryPort_ListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRepositoryPort_ListRefunds_Call) Return(_a0 []payment.Refund, _a1 int64, _a2 error) *MockRepositoryPort_ListRefunds_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepositoryPort_ListRefunds_Call) RunAndReturn(run func(context.Context, int, int) ([]payment.Refund, int64, error)) *MockRepositoryPort_ListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// LogCallback provides a mock function with given fields: ctx, cb
func (_m *MockRepositoryPort) LogCallback(ctx context.Context, cb *payment.MidtransCallback) error {
	ret := _m.Called(ctx, cb)

	if len(ret) == 0 {
		panic("no return value specified for LogCallback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.MidtransCallback) error); ok {
		r0 = rf(ctx, cb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryPort_LogCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogCallback'
type MockRepositoryPort_LogCallback_Call struct {
	*mock.Call
}

// LogCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - cb *payment.MidtransCallback
func (_e *MockRepositoryPort_Expecter) LogCallback(ctx interface{}, cb interface{}) *MockRepositoryPort_LogCallback_Call {
	return &MockRepositoryPort_LogCallback_Call{Call: _e.mock.On("LogCallback", ctx, cb)}
}

func (_c *MockRepositoryPort_LogCallback_Call) Run(run func(ctx context.Context, cb *payment.MidtransCallback)) *MockRepositoryPort_LogCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*payment.MidtransCallback))
	})
	return _c
}

func (_c *MockRepositoryPort_LogCallback_Call) Return(_a0 error) *MockRepositoryPort_LogCallback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryPort_LogCallback_Call) RunAndReturn(run func(context.Context, *payment.MidtransCallback) error) *MockRepositoryPort_LogCallback_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCallback provides a mock function with given fields: ctx, cb
func (_m *MockRepositoryPort) UpdateCallback(ctx context.Context, cb *payment.MidtransCallback) error {
	ret := _m.Called(ctx, cb)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCallback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.MidtransCallback) error); ok {
		r0 = rf(ctx, cb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryPort_UpdateCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCallback'
type MockRepositoryPort_UpdateCallback_Call struct {
	*mock.Call
}

// UpdateCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - cb *payment.MidtransCallback
func (_e *MockRepositoryPort_Expecter) UpdateCallback(ctx interface{}, cb interface{}) *MockRepositoryPort_UpdateCallback_Call {
	return &MockRepositoryPort_UpdateCallback_Call{Call: _e.mock.On("UpdateCallback", ctx, cb)}
}

func (_c *MockRepositoryPort_UpdateCallback_Call) Run(run func(ctx context.Context, cb *payment.MidtransCallback)) *MockRepositoryPort_UpdateCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*payment.MidtransCallback))
	})
	return _c
}

func (_c *MockRepositoryPort_UpdateCallback_Call) Return(_a0 error) *MockRepositoryPort_UpdateCallback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryPort_UpdateCallback_Call) RunAndReturn(run func(context.Context, *payment.MidtransCallback) error) *MockRepositoryPort_UpdateCallback_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePayment provides a mock function with given fields: ctx, p
func (_m *MockRepositoryPort) UpdatePayment(ctx context.Context, p *payment.Payment) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryPort_UpdatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePayment'
type MockRepositoryPort_UpdatePayment_Call struct {
	*mock.Call
}

// UpdatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - p *payment.Payment
func (_e *MockRepositoryPort_Expecter) UpdatePayment(ctx interface{}, p interface{}) *MockRepositoryPort_UpdatePayment_Call {
	return &MockRepositoryPort_UpdatePayment_Call{Call: _e.mock.On("UpdatePayment", ctx, p)}
}

func (_c *MockRepositoryPort_UpdatePayment_Call) Run(run func(ctx context.Context, p *payment.Payment)) *MockRepositoryPort_UpdatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*payment.Payment))
	})
	return _c
}

func (_c *MockRepositoryPort_UpdatePayment_Call) Return(_a0 error) *MockRepositoryPort_UpdatePayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryPort_UpdatePayment_Call) RunAndReturn(run func(context.Context, *payment.Payment) error) *MockRepositoryPort_UpdatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRefund provides a mock function with given fields: ctx, r
func (_m *MockRepositoryPort) UpdateRefund(ctx context.Context, r *payment.Refund) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRefund")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.Refund) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryPort_UpdateRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRefund'
type MockRepositoryPort_UpdateRefund_Call struct {
	*mock.Call
}

// UpdateRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - r *payment.Refund
func (_e *MockRepositoryPort_Expecter) UpdateRefund(ctx interface{}, r interface{}) *MockRepositoryPort_UpdateRefund_Call {
	return &MockRepositoryPort_UpdateRefund_Call{Call: _e.mock.On("UpdateRefund", ctx, r)}
}

func (_c *MockRepositoryPort_UpdateRefund_Call) Run(run func(ctx context.Context, r *payment.Refund)) *MockRepositoryPort_UpdateRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*payment.Refund))
	})
	return _c
}

func (_c *MockRepositoryPort_UpdateRefund_Call) Return(_a0 error) *MockRepositoryPort_UpdateRefund_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryPort_UpdateRefund_Call) RunAndReturn(run func(context.Context, *payment.Refund) error) *MockRepositoryPort_UpdateRefund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryPort creates a new instance of MockRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryPort {
	mock := &MockRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
