// Code generated by mockery. DO NOT EDIT.

package auth

import (
	context "context"
	auth "parkieee/internal/modules/auth"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockSessionRepositoryPort is an autogenerated mock type for the SessionRepositoryPort type
type MockSessionRepositoryPort struct {
	mock.Mock
}

type MockSessionRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepositoryPort) EXPECT() *MockSessionRepositoryPort_Expecter {
	return &MockSessionRepositoryPort_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session
func (_m *MockSessionRepositoryPort) Create(ctx context.Context, session *auth.UserSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.UserSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepositoryPort_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepositoryPort_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *auth.UserSession
func (_e *MockSessionRepositoryPort_Expecter) Create(ctx interface{}, session interface{}) *MockSessionRepositoryPort_Create_Call {
	return &MockSessionRepositoryPort_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockSessionRepositoryPort_Create_Call) Run(run func(ctx context.Context, session *auth.UserSession)) *MockSessionRepositoryPort_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.UserSession))
	})
	return _c
}

func (_c *MockSessionRepositoryPort_Create_Call) Return(_a0 error) *MockSessionRepositoryPort_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepositoryPort_Create_Call) RunAndReturn(run func(context.Context, *auth.UserSession) error) *MockSessionRepositoryPort_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with given fields: ctx, before
func (_m *MockSessionRepositoryPort) DeleteExpired(ctx context.Context, before time.Time) error {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepositoryPort_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockSessionRepositoryPort_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockSessionRepositoryPort_Expecter) DeleteExpired(ctx interface{}, before interface{}) *MockSessionRepositoryPort_DeleteExpired_Call {
	return &MockSessionRepositoryPort_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx, before)}
}

func (_c *MockSessionRepositoryPort_DeleteExpired_Call) Run(run func(ctx context.Context, before time.Time)) *MockSessionRepositoryPort_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockSessionRepositoryPort_DeleteExpired_Call) Return(_a0 error) *MockSessionRepositoryPort_DeleteExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepositoryPort_DeleteExpired_Call) RunAndReturn(run func(context.Context, time.Time) error) *MockSessionRepositoryPort_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockSessionRepositoryPort) FindByTokenHash(ctx context.Context, tokenHash string) (*auth.UserSession, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByTokenHash")
	}

	var r0 *auth.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.UserSession, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.UserSession); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepositoryPort_FindByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTokenHash'
type MockSessionRepositoryPort_FindByTokenHash_Call struct {
	*mock.Call
}

// FindByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockSessionRepositoryPort_Expecter) FindByTokenHash(ctx interface{}, tokenHash interface{}) *MockSessionRepositoryPort_FindByTokenHash_Call {
	return &MockSessionRepositoryPort_FindByTokenHash_Call{Call: _e.mock.On("FindByTokenHash", ctx, tokenHash)}
}

func (_c *MockSessionRepositoryPort_FindByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockSessionRepositoryPort_FindByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepositoryPort_FindByTokenHash_Call) Return(_a0 *auth.UserSession, _a1 error) *MockSessionRepositoryPort_FindByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepositoryPort_FindByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*auth.UserSession, error)) *MockSessionRepositoryPort_FindByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, id
func (_m *MockSessionRepositoryPort) Revoke(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepositoryPort_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockSessionRepositoryPort_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSessionRepositoryPort_Expecter) Revoke(ctx interface{}, id interface{}) *MockSessionRepositoryPort_Revoke_Call {
	return &MockSessionRepositoryPort_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *MockSessionRepositoryPort_Revoke_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSessionRepositoryPort_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionRepositoryPort_Revoke_Call) Return(_a0 error) *MockSessionRepositoryPort_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepositoryPort_Revoke_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSessionRepositoryPort_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllByUserID provides a mock function with given fields: ctx, userID
func (_m *MockSessionRepositoryPort) RevokeAllByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepositoryPort_RevokeAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllByUserID'
type MockSessionRepositoryPort_RevokeAllByUserID_Call struct {
	*mock.Call
}

// RevokeAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSessionRepositoryPort_Expecter) RevokeAllByUserID(ctx interface{}, userID interface{}) *MockSessionRepositoryPort_RevokeAllByUserID_Call {
	return &MockSessionRepositoryPort_RevokeAllByUserID_Call{Call: _e.mock.On("RevokeAllByUserID", ctx, userID)}
}

func (_c *MockSessionRepositoryPort_RevokeAllByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSessionRepositoryPort_RevokeAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionRepositoryPort_RevokeAllByUserID_Call) Return(_a0 error) *MockSessionRepositoryPort_RevokeAllByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepositoryPort_RevokeAllByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSessionRepositoryPort_RevokeAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepositoryPort creates a new instance of MockSessionRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepositoryPort {
	mock := &MockSessionRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
