// Code generated by mockery. DO NOT EDIT.

package auth

import (
	context "context"
	auth "parkieee/internal/modules/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockLoginLogRepositoryPort is an autogenerated mock type for the LoginLogRepositoryPort type
type MockLoginLogRepositoryPort struct {
	mock.Mock
}

type MockLoginLogRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginLogRepositoryPort) EXPECT() *MockLoginLogRepositoryPort_Expecter {
	return &MockLoginLogRepositoryPort_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: ctx, log
func (_m *MockLoginLogRepositoryPort) Append(ctx context.Context, log *auth.UserLoginLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.UserLoginLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoginLogRepositoryPort_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockLoginLogRepositoryPort_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - log *auth.UserLoginLog
func (_e *MockLoginLogRepositoryPort_Expecter) Append(ctx interface{}, log interface{}) *MockLoginLogRepositoryPort_Append_Call {
	return &MockLoginLogRepositoryPort_Append_Call{Call: _e.mock.On("Append", ctx, log)}
}

func (_c *MockLoginLogRepositoryPort_Append_Call) Run(run func(ctx context.Context, log *auth.UserLoginLog)) *MockLoginLogRepositoryPort_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.UserLoginLog))
	})
	return _c
}

func (_c *MockLoginLogRepositoryPort_Append_Call) Return(_a0 error) *MockLoginLogRepositoryPort_Append_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoginLogRepositoryPort_Append_Call) RunAndReturn(run func(context.Context, *auth.UserLoginLog) error) *MockLoginLogRepositoryPort_Append_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginLogRepositoryPort creates a new instance of MockLoginLogRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginLogRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginLogRepositoryPort {
	mock := &MockLoginLogRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
