// Code generated by mockery. DO NOT EDIT.

package auth

import (
	context "context"
	auth "parkieee/internal/modules/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserRepositoryPort is an autogenerated mock type for the UserRepositoryPort type
type MockUserRepositoryPort struct {
	mock.Mock
}

type MockUserRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryPort) EXPECT() *MockUserRepositoryPort_Expecter {
	return &MockUserRepositoryPort_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserRepositoryPort) Create(ctx context.Context, user *auth.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryPort_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepositoryPort_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *auth.User
func (_e *MockUserRepositoryPort_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepositoryPort_Create_Call {
	return &MockUserRepositoryPort_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepositoryPort_Create_Call) Run(run func(ctx context.Context, user *auth.User)) *MockUserRepositoryPort_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.User))
	})
	return _c
}

func (_c *MockUserRepositoryPort_Create_Call) Return(_a0 error) *MockUserRepositoryPort_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryPort_Create_Call) RunAndReturn(run func(context.Context, *auth.User) error) *MockUserRepositoryPort_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepositoryPort) FindByEmail(ctx context.Context, email string) (*auth.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryPort_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepositoryPort_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepositoryPort_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepositoryPort_FindByEmail_Call {
	return &MockUserRepositoryPort_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepositoryPort_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepositoryPort_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepositoryPort_FindByEmail_Call) Return(_a0 *auth.User, _a1 error) *MockUserRepositoryPort_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryPort_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (*auth.User, error)) *MockUserRepositoryPort_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepositoryPort) FindByID(ctx context.Context, id uuid.UUID) (*auth.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*auth.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *auth.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryPort_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepositoryPort_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepositoryPort_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepositoryPort_FindByID_Call {
	return &MockUserRepositoryPort_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepositoryPort_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepositoryPort_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepositoryPort_FindByID_Call) Return(_a0 *auth.User, _a1 error) *MockUserRepositoryPort_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryPort_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*auth.User, error)) *MockUserRepositoryPort_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockUserRepositoryPort) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryPort_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockUserRepositoryPort_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepositoryPort_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockUserRepositoryPort_SoftDelete_Call {
	return &MockUserRepositoryPort_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockUserRepositoryPort_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepositoryPort_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepositoryPort_SoftDelete_Call) Return(_a0 error) *MockUserRepositoryPort_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryPort_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserRepositoryPort_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockUserRepositoryPort) Update(ctx context.Context, user *auth.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryPort_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepositoryPort_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *auth.User
func (_e *MockUserRepositoryPort_Expecter) Update(ctx interface{}, user interface{}) *MockUserRepositoryPort_Update_Call {
	return &MockUserRepositoryPort_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserRepositoryPort_Update_Call) Run(run func(ctx context.Context, user *auth.User)) *MockUserRepositoryPort_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.User))
	})
	return _c
}

func (_c *MockUserRepositoryPort_Update_Call) Return(_a0 error) *MockUserRepositoryPort_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryPort_Update_Call) RunAndReturn(run func(context.Context, *auth.User) error) *MockUserRepositoryPort_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepositoryPort creates a new instance of MockUserRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryPort {
	mock := &MockUserRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
