// Code generated by mockery. DO NOT EDIT.

package auth

import (
	context "context"
	auth "parkieee/internal/modules/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockLoginStatsRepositoryPort is an autogenerated mock type for the LoginStatsRepositoryPort type
type MockLoginStatsRepositoryPort struct {
	mock.Mock
}

type MockLoginStatsRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginStatsRepositoryPort) EXPECT() *MockLoginStatsRepositoryPort_Expecter {
	return &MockLoginStatsRepositoryPort_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockLoginStatsRepositoryPort) FindByUserID(ctx context.Context, userID uuid.UUID) (*auth.UserLoginStats, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *auth.UserLoginStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*auth.UserLoginStats, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *auth.UserLoginStats); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.UserLoginStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginStatsRepositoryPort_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockLoginStatsRepositoryPort_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockLoginStatsRepositoryPort_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockLoginStatsRepositoryPort_FindByUserID_Call {
	return &MockLoginStatsRepositoryPort_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockLoginStatsRepositoryPort_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockLoginStatsRepositoryPort_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLoginStatsRepositoryPort_FindByUserID_Call) Return(_a0 *auth.UserLoginStats, _a1 error) *MockLoginStatsRepositoryPort_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginStatsRepositoryPort_FindByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*auth.UserLoginStats, error)) *MockLoginStatsRepositoryPort_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, stats
func (_m *MockLoginStatsRepositoryPort) Upsert(ctx context.Context, stats *auth.UserLoginStats) error {
	ret := _m.Called(ctx, stats)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.UserLoginStats) error); ok {
		r0 = rf(ctx, stats)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoginStatsRepositoryPort_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockLoginStatsRepositoryPort_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - stats *auth.UserLoginStats
func (_e *MockLoginStatsRepositoryPort_Expecter) Upsert(ctx interface{}, stats interface{}) *MockLoginStatsRepositoryPort_Upsert_Call {
	return &MockLoginStatsRepositoryPort_Upsert_Call{Call: _e.mock.On("Upsert", ctx, stats)}
}

func (_c *MockLoginStatsRepositoryPort_Upsert_Call) Run(run func(ctx context.Context, stats *auth.UserLoginStats)) *MockLoginStatsRepositoryPort_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.UserLoginStats))
	})
	return _c
}

func (_c *MockLoginStatsRepositoryPort_Upsert_Call) Return(_a0 error) *MockLoginStatsRepositoryPort_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoginStatsRepositoryPort_Upsert_Call) RunAndReturn(run func(context.Context, *auth.UserLoginStats) error) *MockLoginStatsRepositoryPort_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginStatsRepositoryPort creates a new instance of MockLoginStatsRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginStatsRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginStatsRepositoryPort {
	mock := &MockLoginStatsRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
