// Code generated by mockery. DO NOT EDIT.

package auth

import (
	context "context"
	auth "parkieee/internal/modules/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPermissionRepositoryPort is an autogenerated mock type for the PermissionRepositoryPort type
type MockPermissionRepositoryPort struct {
	mock.Mock
}

type MockPermissionRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionRepositoryPort) EXPECT() *MockPermissionRepositoryPort_Expecter {
	return &MockPermissionRepositoryPort_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockPermissionRepositoryPort) FindAll(ctx context.Context) ([]auth.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []auth.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]auth.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []auth.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auth.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepositoryPort_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockPermissionRepositoryPort_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPermissionRepositoryPort_Expecter) FindAll(ctx interface{}) *MockPermissionRepositoryPort_FindAll_Call {
	return &MockPermissionRepositoryPort_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockPermissionRepositoryPort_FindAll_Call) Run(run func(ctx context.Context)) *MockPermissionRepositoryPort_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPermissionRepositoryPort_FindAll_Call) Return(_a0 []auth.Permission, _a1 error) *MockPermissionRepositoryPort_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepositoryPort_FindAll_Call) RunAndReturn(run func(context.Context) ([]auth.Permission, error)) *MockPermissionRepositoryPort_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockPermissionRepositoryPort) FindByID(ctx context.Context, id uuid.UUID) (*auth.Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *auth.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*auth.Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *auth.Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepositoryPort_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPermissionRepositoryPort_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPermissionRepositoryPort_Expecter) FindByID(ctx interface{}, id interface{}) *MockPermissionRepositoryPort_FindByID_Call {
	return &MockPermissionRepositoryPort_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPermissionRepositoryPort_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPermissionRepositoryPort_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPermissionRepositoryPort_FindByID_Call) Return(_a0 *auth.Permission, _a1 error) *MockPermissionRepositoryPort_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepositoryPort_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*auth.Permission, error)) *MockPermissionRepositoryPort_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNode provides a mock function with given fields: ctx, node
func (_m *MockPermissionRepositoryPort) FindByNode(ctx context.Context, node string) (*auth.Permission, error) {
	ret := _m.Called(ctx, node)

	if len(ret) == 0 {
		panic("no return value specified for FindByNode")
	}

	var r0 *auth.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.Permission, error)); ok {
		return rf(ctx, node)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.Permission); ok {
		r0 = rf(ctx, node)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, node)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepositoryPort_FindByNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNode'
type MockPermissionRepositoryPort_FindByNode_Call struct {
	*mock.Call
}

// FindByNode is a helper method to define mock.On call
//   - ctx context.Context
//   - node string
func (_e *MockPermissionRepositoryPort_Expecter) FindByNode(ctx interface{}, node interface{}) *MockPermissionRepositoryPort_FindByNode_Call {
	return &MockPermissionRepositoryPort_FindByNode_Call{Call: _e.mock.On("FindByNode", ctx, node)}
}

func (_c *MockPermissionRepositoryPort_FindByNode_Call) Run(run func(ctx context.Context, node string)) *MockPermissionRepositoryPort_FindByNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPermissionRepositoryPort_FindByNode_Call) Return(_a0 *auth.Permission, _a1 error) *MockPermissionRepositoryPort_FindByNode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepositoryPort_FindByNode_Call) RunAndReturn(run func(context.Context, string) (*auth.Permission, error)) *MockPermissionRepositoryPort_FindByNode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPermissionRepositoryPort creates a new instance of MockPermissionRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionRepositoryPort {
	mock := &MockPermissionRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
