// Code generated by mockery. DO NOT EDIT.

package auth

import (
	context "context"
	auth "parkieee/internal/modules/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRolePermissionRepositoryPort is an autogenerated mock type for the RolePermissionRepositoryPort type
type MockRolePermissionRepositoryPort struct {
	mock.Mock
}

type MockRolePermissionRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolePermissionRepositoryPort) EXPECT() *MockRolePermissionRepositoryPort_Expecter {
	return &MockRolePermissionRepositoryPort_Expecter{mock: &_m.Mock}
}

// Assign provides a mock function with given fields: ctx, roleID, permissionID, grantedBy
func (_m *MockRolePermissionRepositoryPort) Assign(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID, grantedBy uuid.UUID) error {
	ret := _m.Called(ctx, roleID, permissionID, grantedBy)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roleID, permissionID, grantedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRolePermissionRepositoryPort_Assign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assign'
type MockRolePermissionRepositoryPort_Assign_Call struct {
	*mock.Call
}

// Assign is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permissionID uuid.UUID
//   - grantedBy uuid.UUID
func (_e *MockRolePermissionRepositoryPort_Expecter) Assign(ctx interface{}, roleID interface{}, permissionID interface{}, grantedBy interface{}) *MockRolePermissionRepositoryPort_Assign_Call {
	return &MockRolePermissionRepositoryPort_Assign_Call{Call: _e.mock.On("Assign", ctx, roleID, permissionID, grantedBy)}
}

func (_c *MockRolePermissionRepositoryPort_Assign_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID, grantedBy uuid.UUID)) *MockRolePermissionRepositoryPort_Assign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockRolePermissionRepositoryPort_Assign_Call) Return(_a0 error) *MockRolePermissionRepositoryPort_Assign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRolePermissionRepositoryPort_Assign_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockRolePermissionRepositoryPort_Assign_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRoleID provides a mock function with given fields: ctx, roleID
func (_m *MockRolePermissionRepositoryPort) FindByRoleID(ctx context.Context, roleID uuid.UUID) ([]auth.RolePermission, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for FindByRoleID")
	}

	var r0 []auth.RolePermission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]auth.RolePermission, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []auth.RolePermission); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auth.RolePermission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolePermissionRepositoryPort_FindByRoleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRoleID'
type MockRolePermissionRepositoryPort_FindByRoleID_Call struct {
	*mock.Call
}

// FindByRoleID is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
func (_e *MockRolePermissionRepositoryPort_Expecter) FindByRoleID(ctx interface{}, roleID interface{}) *MockRolePermissionRepositoryPort_FindByRoleID_Call {
	return &MockRolePermissionRepositoryPort_FindByRoleID_Call{Call: _e.mock.On("FindByRoleID", ctx, roleID)}
}

func (_c *MockRolePermissionRepositoryPort_FindByRoleID_Call) Run(run func(ctx context.Context, roleID uuid.UUID)) *MockRolePermissionRepositoryPort_FindByRoleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRolePermissionRepositoryPort_FindByRoleID_Call) Return(_a0 []auth.RolePermission, _a1 error) *MockRolePermissionRepositoryPort_FindByRoleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolePermissionRepositoryPort_FindByRoleID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]auth.RolePermission, error)) *MockRolePermissionRepositoryPort_FindByRoleID_Call {
	_c.Call.Return(run)
	return _c
}

// HasPermission provides a mock function with given fields: ctx, roleID, node
func (_m *MockRolePermissionRepositoryPort) HasPermission(ctx context.Context, roleID uuid.UUID, node string) (bool, error) {
	ret := _m.Called(ctx, roleID, node)

	if len(ret) == 0 {
		panic("no return value specified for HasPermission")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return rf(ctx, roleID, node)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = rf(ctx, roleID, node)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, roleID, node)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRolePermissionRepositoryPort_HasPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPermission'
type MockRolePermissionRepositoryPort_HasPermission_Call struct {
	*mock.Call
}

// HasPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - node string
func (_e *MockRolePermissionRepositoryPort_Expecter) HasPermission(ctx interface{}, roleID interface{}, node interface{}) *MockRolePermissionRepositoryPort_HasPermission_Call {
	return &MockRolePermissionRepositoryPort_HasPermission_Call{Call: _e.mock.On("HasPermission", ctx, roleID, node)}
}

func (_c *MockRolePermissionRepositoryPort_HasPermission_Call) Run(run func(ctx context.Context, roleID uuid.UUID, node string)) *MockRolePermissionRepositoryPort_HasPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRolePermissionRepositoryPort_HasPermission_Call) Return(_a0 bool, _a1 error) *MockRolePermissionRepositoryPort_HasPermission_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRolePermissionRepositoryPort_HasPermission_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (bool, error)) *MockRolePermissionRepositoryPort_HasPermission_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, roleID, permissionID
func (_m *MockRolePermissionRepositoryPort) Revoke(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) error {
	ret := _m.Called(ctx, roleID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roleID, permissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRolePermissionRepositoryPort_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockRolePermissionRepositoryPort_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permissionID uuid.UUID
func (_e *MockRolePermissionRepositoryPort_Expecter) Revoke(ctx interface{}, roleID interface{}, permissionID interface{}) *MockRolePermissionRepositoryPort_Revoke_Call {
	return &MockRolePermissionRepositoryPort_Revoke_Call{Call: _e.mock.On("Revoke", ctx, roleID, permissionID)}
}

func (_c *MockRolePermissionRepositoryPort_Revoke_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID)) *MockRolePermissionRepositoryPort_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRolePermissionRepositoryPort_Revoke_Call) Return(_a0 error) *MockRolePermissionRepositoryPort_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRolePermissionRepositoryPort_Revoke_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockRolePermissionRepositoryPort_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRolePermissionRepositoryPort creates a new instance of MockRolePermissionRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolePermissionRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolePermissionRepositoryPort {
	mock := &MockRolePermissionRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
