// Code generated by mockery. DO NOT EDIT.

package auth

import (
	context "context"
	auth "parkieee/internal/modules/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRoleRepositoryPort is an autogenerated mock type for the RoleRepositoryPort type
type MockRoleRepositoryPort struct {
	mock.Mock
}

type MockRoleRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepositoryPort) EXPECT() *MockRoleRepositoryPort_Expecter {
	return &MockRoleRepositoryPort_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, role
func (_m *MockRoleRepositoryPort) Create(ctx context.Context, role *auth.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepositoryPort_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleRepositoryPort_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role *auth.Role
func (_e *MockRoleRepositoryPort_Expecter) Create(ctx interface{}, role interface{}) *MockRoleRepositoryPort_Create_Call {
	return &MockRoleRepositoryPort_Create_Call{Call: _e.mock.On("Create", ctx, role)}
}

func (_c *MockRoleRepositoryPort_Create_Call) Run(run func(ctx context.Context, role *auth.Role)) *MockRoleRepositoryPort_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.Role))
	})
	return _c
}

func (_c *MockRoleRepositoryPort_Create_Call) Return(_a0 error) *MockRoleRepositoryPort_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepositoryPort_Create_Call) RunAndReturn(run func(context.Context, *auth.Role) error) *MockRoleRepositoryPort_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockRoleRepositoryPort) FindAll(ctx context.Context) ([]auth.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []auth.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]auth.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []auth.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auth.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepositoryPort_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRoleRepositoryPort_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepositoryPort_Expecter) FindAll(ctx interface{}) *MockRoleRepositoryPort_FindAll_Call {
	return &MockRoleRepositoryPort_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockRoleRepositoryPort_FindAll_Call) Run(run func(ctx context.Context)) *MockRoleRepositoryPort_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepositoryPort_FindAll_Call) Return(_a0 []auth.Role, _a1 error) *MockRoleRepositoryPort_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepositoryPort_FindAll_Call) RunAndReturn(run func(context.Context) ([]auth.Role, error)) *MockRoleRepositoryPort_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRoleRepositoryPort) FindByID(ctx context.Context, id uuid.UUID) (*auth.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *auth.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*auth.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *auth.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepositoryPort_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoleRepositoryPort_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRoleRepositoryPort_Expecter) FindByID(ctx interface{}, id interface{}) *MockRoleRepositoryPort_FindByID_Call {
	return &MockRoleRepositoryPort_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoleRepositoryPort_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRoleRepositoryPort_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoleRepositoryPort_FindByID_Call) Return(_a0 *auth.Role, _a1 error) *MockRoleRepositoryPort_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepositoryPort_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*auth.Role, error)) *MockRoleRepositoryPort_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockRoleRepositoryPort) FindByName(ctx context.Context, name string) (*auth.Role, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *auth.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.Role, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.Role); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepositoryPort_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockRoleRepositoryPort_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepositoryPort_Expecter) FindByName(ctx interface{}, name interface{}) *MockRoleRepositoryPort_FindByName_Call {
	return &MockRoleRepositoryPort_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockRoleRepositoryPort_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepositoryPort_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepositoryPort_FindByName_Call) Return(_a0 *auth.Role, _a1 error) *MockRoleRepositoryPort_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepositoryPort_FindByName_Call) RunAndReturn(run func(context.Context, string) (*auth.Role, error)) *MockRoleRepositoryPort_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepositoryPort creates a new instance of MockRoleRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepositoryPort {
	mock := &MockRoleRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
