// Code generated by mockery. DO NOT EDIT.

package zone

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	zone "parkieee/internal/modules/zone"
)

// MockGateRepositoryPort is an autogenerated mock type for the GateRepositoryPort type
type MockGateRepositoryPort struct {
	mock.Mock
}

type MockGateRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateRepositoryPort) EXPECT() *MockGateRepositoryPort_Expecter {
	return &MockGateRepositoryPort_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, gate
func (_m *MockGateRepositoryPort) Create(ctx context.Context, gate *zone.Gate) error {
	ret := _m.Called(ctx, gate)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *zone.Gate) error); ok {
		r0 = rf(ctx, gate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateRepositoryPort_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGateRepositoryPort_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - gate *zone.Gate
func (_e *MockGateRepositoryPort_Expecter) Create(ctx interface{}, gate interface{}) *MockGateRepositoryPort_Create_Call {
	return &MockGateRepositoryPort_Create_Call{Call: _e.mock.On("Create", ctx, gate)}
}

func (_c *MockGateRepositoryPort_Create_Call) Run(run func(ctx context.Context, gate *zone.Gate)) *MockGateRepositoryPort_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*zone.Gate))
	})
	return _c
}

func (_c *MockGateRepositoryPort_Create_Call) Return(_a0 error) *MockGateRepositoryPort_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateRepositoryPort_Create_Call) RunAndReturn(run func(context.Context, *zone.Gate) error) *MockGateRepositoryPort_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function with given fields: ctx, id
func (_m *MockGateRepositoryPort) Deactivate(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateRepositoryPort_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockGateRepositoryPort_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGateRepositoryPort_Expecter) Deactivate(ctx interface{}, id interface{}) *MockGateRepositoryPort_Deactivate_Call {
	return &MockGateRepositoryPort_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, id)}
}

func (_c *MockGateRepositoryPort_Deactivate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGateRepositoryPort_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGateRepositoryPort_Deactivate_Call) Return(_a0 error) *MockGateRepositoryPort_Deactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateRepositoryPort_Deactivate_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGateRepositoryPort_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockGateRepositoryPort) FindByID(ctx context.Context, id uuid.UUID) (*zone.Gate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *zone.Gate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*zone.Gate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *zone.Gate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zone.Gate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGateRepositoryPort_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockGateRepositoryPort_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGateRepositoryPort_Expecter) FindByID(ctx interface{}, id interface{}) *MockGateRepositoryPort_FindByID_Call {
	return &MockGateRepositoryPort_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockGateRepositoryPort_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGateRepositoryPort_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGateRepositoryPort_FindByID_Call) Return(_a0 *zone.Gate, _a1 error) *MockGateRepositoryPort_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGateRepositoryPort_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*zone.Gate, error)) *MockGateRepositoryPort_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function with given fields: ctx, token
func (_m *MockGateRepositoryPort) FindByToken(ctx context.Context, token string) (*zone.Gate, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *zone.Gate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*zone.Gate, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *zone.Gate); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zone.Gate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGateRepositoryPort_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockGateRepositoryPort_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockGateRepositoryPort_Expecter) FindByToken(ctx interface{}, token interface{}) *MockGateRepositoryPort_FindByToken_Call {
	return &MockGateRepositoryPort_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *MockGateRepositoryPort_FindByToken_Call) Run(run func(ctx context.Context, token string)) *MockGateRepositoryPort_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGateRepositoryPort_FindByToken_Call) Return(_a0 *zone.Gate, _a1 error) *MockGateRepositoryPort_FindByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGateRepositoryPort_FindByToken_Call) RunAndReturn(run func(context.Context, string) (*zone.Gate, error)) *MockGateRepositoryPort_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindByZoneID provides a mock function with given fields: ctx, zoneID, onlyActive, page, pageSize
func (_m *MockGateRepositoryPort) FindByZoneID(ctx context.Context, zoneID uuid.UUID, onlyActive bool, page int, pageSize int) ([]zone.Gate, int64, error) {
	ret := _m.Called(ctx, zoneID, onlyActive, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindByZoneID")
	}

	var r0 []zone.Gate
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, int, int) ([]zone.Gate, int64, error)); ok {
		return rf(ctx, zoneID, onlyActive, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, int, int) []zone.Gate); ok {
		r0 = rf(ctx, zoneID, onlyActive, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]zone.Gate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool, int, int) int64); ok {
		r1 = rf(ctx, zoneID, onlyActive, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, bool, int, int) error); ok {
		r2 = rf(ctx, zoneID, onlyActive, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockGateRepositoryPort_FindByZoneID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByZoneID'
type MockGateRepositoryPort_FindByZoneID_Call struct {
	*mock.Call
}

// FindByZoneID is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID uuid.UUID
//   - onlyActive bool
//   - page int
//   - pageSize int
func (_e *MockGateRepositoryPort_Expecter) FindByZoneID(ctx interface{}, zoneID interface{}, onlyActive interface{}, page interface{}, pageSize interface{}) *MockGateRepositoryPort_FindByZoneID_Call {
	return &MockGateRepositoryPort_FindByZoneID_Call{Call: _e.mock.On("FindByZoneID", ctx, zoneID, onlyActive, page, pageSize)}
}

func (_c *MockGateRepositoryPort_FindByZoneID_Call) Run(run func(ctx context.Context, zoneID uuid.UUID, onlyActive bool, page int, pageSize int)) *MockGateRepositoryPort_FindByZoneID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockGateRepositoryPort_FindByZoneID_Call) Return(_a0 []zone.Gate, _a1 int64, _a2 error) *MockGateRepositoryPort_FindByZoneID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockGateRepositoryPort_FindByZoneID_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool, int, int) ([]zone.Gate, int64, error)) *MockGateRepositoryPort_FindByZoneID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, gate
func (_m *MockGateRepositoryPort) Update(ctx context.Context, gate *zone.Gate) error {
	ret := _m.Called(ctx, gate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *zone.Gate) error); ok {
		r0 = rf(ctx, gate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateRepositoryPort_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGateRepositoryPort_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - gate *zone.Gate
func (_e *MockGateRepositoryPort_Expecter) Update(ctx interface{}, gate interface{}) *MockGateRepositoryPort_Update_Call {
	return &MockGateRepositoryPort_Update_Call{Call: _e.mock.On("Update", ctx, gate)}
}

func (_c *MockGateRepositoryPort_Update_Call) Run(run func(ctx context.Context, gate *zone.Gate)) *MockGateRepositoryPort_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*zone.Gate))
	})
	return _c
}

func (_c *MockGateRepositoryPort_Update_Call) Return(_a0 error) *MockGateRepositoryPort_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateRepositoryPort_Update_Call) RunAndReturn(run func(context.Context, *zone.Gate) error) *MockGateRepositoryPort_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTokenLastUsed provides a mock function with given fields: ctx, id
func (_m *MockGateRepositoryPort) UpdateTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTokenLastUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateRepositoryPort_UpdateTokenLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTokenLastUsed'
type MockGateRepositoryPort_UpdateTokenLastUsed_Call struct {
	*mock.Call
}

// UpdateTokenLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGateRepositoryPort_Expecter) UpdateTokenLastUsed(ctx interface{}, id interface{}) *MockGateRepositoryPort_UpdateTokenLastUsed_Call {
	return &MockGateRepositoryPort_UpdateTokenLastUsed_Call{Call: _e.mock.On("UpdateTokenLastUsed", ctx, id)}
}

func (_c *MockGateRepositoryPort_UpdateTokenLastUsed_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGateRepositoryPort_UpdateTokenLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGateRepositoryPort_UpdateTokenLastUsed_Call) Return(_a0 error) *MockGateRepositoryPort_UpdateTokenLastUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateRepositoryPort_UpdateTokenLastUsed_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGateRepositoryPort_UpdateTokenLastUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGateRepositoryPort creates a new instance of MockGateRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateRepositoryPort {
	mock := &MockGateRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
