// Code generated by mockery. DO NOT EDIT.

package zone

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	zone "parkieee/internal/modules/zone"
)

// MockZoneRepositoryPort is an autogenerated mock type for the ZoneRepositoryPort type
type MockZoneRepositoryPort struct {
	mock.Mock
}

type MockZoneRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockZoneRepositoryPort) EXPECT() *MockZoneRepositoryPort_Expecter {
	return &MockZoneRepositoryPort_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockZoneRepositoryPort) Create(ctx context.Context, _a1 *zone.Zone) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *zone.Zone) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockZoneRepositoryPort_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockZoneRepositoryPort_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *zone.Zone
func (_e *MockZoneRepositoryPort_Expecter) Create(ctx interface{}, _a1 interface{}) *MockZoneRepositoryPort_Create_Call {
	return &MockZoneRepositoryPort_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockZoneRepositoryPort_Create_Call) Run(run func(ctx context.Context, _a1 *zone.Zone)) *MockZoneRepositoryPort_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*zone.Zone))
	})
	return _c
}

func (_c *MockZoneRepositoryPort_Create_Call) Return(_a0 error) *MockZoneRepositoryPort_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockZoneRepositoryPort_Create_Call) RunAndReturn(run func(context.Context, *zone.Zone) error) *MockZoneRepositoryPort_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function with given fields: ctx, id
func (_m *MockZoneRepositoryPort) Deactivate(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockZoneRepositoryPort_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockZoneRepositoryPort_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockZoneRepositoryPort_Expecter) Deactivate(ctx interface{}, id interface{}) *MockZoneRepositoryPort_Deactivate_Call {
	return &MockZoneRepositoryPort_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, id)}
}

func (_c *MockZoneRepositoryPort_Deactivate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockZoneRepositoryPort_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockZoneRepositoryPort_Deactivate_Call) Return(_a0 error) *MockZoneRepositoryPort_Deactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockZoneRepositoryPort_Deactivate_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockZoneRepositoryPort_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, filter, page, pageSize
func (_m *MockZoneRepositoryPort) FindAll(ctx context.Context, filter zone.ListZoneFilter, page int, pageSize int) ([]zone.Zone, int64, error) {
	ret := _m.Called(ctx, filter, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []zone.Zone
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, zone.ListZoneFilter, int, int) ([]zone.Zone, int64, error)); ok {
		return rf(ctx, filter, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, zone.ListZoneFilter, int, int) []zone.Zone); ok {
		r0 = rf(ctx, filter, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]zone.Zone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, zone.ListZoneFilter, int, int) int64); ok {
		r1 = rf(ctx, filter, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, zone.ListZoneFilter, int, int) error); ok {
		r2 = rf(ctx, filter, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockZoneRepositoryPort_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockZoneRepositoryPort_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter zone.ListZoneFilter
//   - page int
//   - pageSize int
func (_e *MockZoneRepositoryPort_Expecter) FindAll(ctx interface{}, filter interface{}, page interface{}, pageSize interface{}) *MockZoneRepositoryPort_FindAll_Call {
	return &MockZoneRepositoryPort_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter, page, pageSize)}
}

func (_c *MockZoneRepositoryPort_FindAll_Call) Run(run func(ctx context.Context, filter zone.ListZoneFilter, page int, pageSize int)) *MockZoneRepositoryPort_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(zone.ListZoneFilter), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockZoneRepositoryPort_FindAll_Call) Return(_a0 []zone.Zone, _a1 int64, _a2 error) *MockZoneRepositoryPort_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockZoneRepositoryPort_FindAll_Call) RunAndReturn(run func(context.Context, zone.ListZoneFilter, int, int) ([]zone.Zone, int64, error)) *MockZoneRepositoryPort_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockZoneRepositoryPort) FindByID(ctx context.Context, id uuid.UUID) (*zone.Zone, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *zone.Zone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*zone.Zone, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *zone.Zone); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zone.Zone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZoneRepositoryPort_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockZoneRepositoryPort_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockZoneRepositoryPort_Expecter) FindByID(ctx interface{}, id interface{}) *MockZoneRepositoryPort_FindByID_Call {
	return &MockZoneRepositoryPort_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockZoneRepositoryPort_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockZoneRepositoryPort_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockZoneRepositoryPort_FindByID_Call) Return(_a0 *zone.Zone, _a1 error) *MockZoneRepositoryPort_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZoneRepositoryPort_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*zone.Zone, error)) *MockZoneRepositoryPort_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockZoneRepositoryPort) Update(ctx context.Context, _a1 *zone.Zone) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *zone.Zone) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockZoneRepositoryPort_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockZoneRepositoryPort_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *zone.Zone
func (_e *MockZoneRepositoryPort_Expecter) Update(ctx interface{}, _a1 interface{}) *MockZoneRepositoryPort_Update_Call {
	return &MockZoneRepositoryPort_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockZoneRepositoryPort_Update_Call) Run(run func(ctx context.Context, _a1 *zone.Zone)) *MockZoneRepositoryPort_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*zone.Zone))
	})
	return _c
}

func (_c *MockZoneRepositoryPort_Update_Call) Return(_a0 error) *MockZoneRepositoryPort_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockZoneRepositoryPort_Update_Call) RunAndReturn(run func(context.Context, *zone.Zone) error) *MockZoneRepositoryPort_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockZoneRepositoryPort creates a new instance of MockZoneRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockZoneRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockZoneRepositoryPort {
	mock := &MockZoneRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
