// Code generated by mockery. DO NOT EDIT.

package zone

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	zone "parkieee/internal/modules/zone"
)

// MockGateCashierAssignmentRepositoryPort is an autogenerated mock type for the GateCashierAssignmentRepositoryPort type
type MockGateCashierAssignmentRepositoryPort struct {
	mock.Mock
}

type MockGateCashierAssignmentRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateCashierAssignmentRepositoryPort) EXPECT() *MockGateCashierAssignmentRepositoryPort_Expecter {
	return &MockGateCashierAssignmentRepositoryPort_Expecter{mock: &_m.Mock}
}

func (_m *MockGateCashierAssignmentRepositoryPort) Upsert(ctx context.Context, a *zone.GateCashierAssignment) error {
	ret := _m.Called(ctx, a)
	return ret.Error(0)
}

type MockGateCashierAssignmentRepositoryPort_Upsert_Call struct {
	*mock.Call
}

func (_e *MockGateCashierAssignmentRepositoryPort_Expecter) Upsert(ctx interface{}, a interface{}) *MockGateCashierAssignmentRepositoryPort_Upsert_Call {
	return &MockGateCashierAssignmentRepositoryPort_Upsert_Call{Call: _e.mock.On("Upsert", ctx, a)}
}

func (_c *MockGateCashierAssignmentRepositoryPort_Upsert_Call) Run(run func(ctx context.Context, a *zone.GateCashierAssignment)) *MockGateCashierAssignmentRepositoryPort_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].(*zone.GateCashierAssignment)) })
	return _c
}

func (_c *MockGateCashierAssignmentRepositoryPort_Upsert_Call) Return(err error) *MockGateCashierAssignmentRepositoryPort_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_m *MockGateCashierAssignmentRepositoryPort) FindByGateID(ctx context.Context, gateID uuid.UUID) (*zone.GateCashierAssignment, error) {
	ret := _m.Called(ctx, gateID)
	var r0 *zone.GateCashierAssignment
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *zone.GateCashierAssignment); ok {
		r0 = rf(ctx, gateID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*zone.GateCashierAssignment)
	}
	return r0, ret.Error(1)
}

type MockGateCashierAssignmentRepositoryPort_FindByGateID_Call struct {
	*mock.Call
}

func (_e *MockGateCashierAssignmentRepositoryPort_Expecter) FindByGateID(ctx interface{}, gateID interface{}) *MockGateCashierAssignmentRepositoryPort_FindByGateID_Call {
	return &MockGateCashierAssignmentRepositoryPort_FindByGateID_Call{Call: _e.mock.On("FindByGateID", ctx, gateID)}
}

func (_c *MockGateCashierAssignmentRepositoryPort_FindByGateID_Call) Return(a *zone.GateCashierAssignment, err error) *MockGateCashierAssignmentRepositoryPort_FindByGateID_Call {
	_c.Call.Return(a, err)
	return _c
}

func (_m *MockGateCashierAssignmentRepositoryPort) FindByUserID(ctx context.Context, userID uuid.UUID) (*zone.GateCashierAssignment, error) {
	ret := _m.Called(ctx, userID)
	var r0 *zone.GateCashierAssignment
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *zone.GateCashierAssignment); ok {
		r0 = rf(ctx, userID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*zone.GateCashierAssignment)
	}
	return r0, ret.Error(1)
}

type MockGateCashierAssignmentRepositoryPort_FindByUserID_Call struct {
	*mock.Call
}

func (_e *MockGateCashierAssignmentRepositoryPort_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockGateCashierAssignmentRepositoryPort_FindByUserID_Call {
	return &MockGateCashierAssignmentRepositoryPort_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockGateCashierAssignmentRepositoryPort_FindByUserID_Call) Return(a *zone.GateCashierAssignment, err error) *MockGateCashierAssignmentRepositoryPort_FindByUserID_Call {
	_c.Call.Return(a, err)
	return _c
}

func (_m *MockGateCashierAssignmentRepositoryPort) DeleteByGateID(ctx context.Context, gateID uuid.UUID) error {
	ret := _m.Called(ctx, gateID)
	return ret.Error(0)
}

type MockGateCashierAssignmentRepositoryPort_DeleteByGateID_Call struct {
	*mock.Call
}

func (_e *MockGateCashierAssignmentRepositoryPort_Expecter) DeleteByGateID(ctx interface{}, gateID interface{}) *MockGateCashierAssignmentRepositoryPort_DeleteByGateID_Call {
	return &MockGateCashierAssignmentRepositoryPort_DeleteByGateID_Call{Call: _e.mock.On("DeleteByGateID", ctx, gateID)}
}

func (_c *MockGateCashierAssignmentRepositoryPort_DeleteByGateID_Call) Return(err error) *MockGateCashierAssignmentRepositoryPort_DeleteByGateID_Call {
	_c.Call.Return(err)
	return _c
}

// NewMockGateCashierAssignmentRepositoryPort creates a new instance of MockGateCashierAssignmentRepositoryPort.
func NewMockGateCashierAssignmentRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateCashierAssignmentRepositoryPort {
	mock := &MockGateCashierAssignmentRepositoryPort{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
