// Code generated by mockery. DO NOT EDIT.

package zone

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	zone "parkieee/internal/modules/zone"
	types "parkieee/pkg/types"
)

// MockGateRepositoryPort is an autogenerated mock type for the GateRepositoryPort type
type MockGateRepositoryPort struct {
	mock.Mock
}

type MockGateRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateRepositoryPort) EXPECT() *MockGateRepositoryPort_Expecter {
	return &MockGateRepositoryPort_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, gate
func (_m *MockGateRepositoryPort) Create(ctx context.Context, gate *zone.Gate) error {
	ret := _m.Called(ctx, gate)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *zone.Gate) error); ok {
		r0 = rf(ctx, gate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockGateRepositoryPort_Expecter) Create(ctx interface{}, gate interface{}) *mock.Call {
	return _e.mock.On("Create", ctx, gate)
}

// Deactivate provides a mock function with given fields: ctx, id
func (_m *MockGateRepositoryPort) Deactivate(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockGateRepositoryPort_Expecter) Deactivate(ctx interface{}, id interface{}) *mock.Call {
	return _e.mock.On("Deactivate", ctx, id)
}

// FindAll provides a mock function with given fields: ctx, filter, page, pageSize
func (_m *MockGateRepositoryPort) FindAll(ctx context.Context, filter zone.ListGateFilter, page int, pageSize int) ([]zone.Gate, int64, error) {
	ret := _m.Called(ctx, filter, page, pageSize)
	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}
	var r0 []zone.Gate
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, zone.ListGateFilter, int, int) ([]zone.Gate, int64, error)); ok {
		return rf(ctx, filter, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, zone.ListGateFilter, int, int) []zone.Gate); ok {
		r0 = rf(ctx, filter, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]zone.Gate)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, zone.ListGateFilter, int, int) int64); ok {
		r1 = rf(ctx, filter, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if rf, ok := ret.Get(2).(func(context.Context, zone.ListGateFilter, int, int) error); ok {
		r2 = rf(ctx, filter, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

func (_e *MockGateRepositoryPort_Expecter) FindAll(ctx interface{}, filter interface{}, page interface{}, pageSize interface{}) *mock.Call {
	return _e.mock.On("FindAll", ctx, filter, page, pageSize)
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockGateRepositoryPort) FindByID(ctx context.Context, id uuid.UUID) (*zone.Gate, error) {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}
	var r0 *zone.Gate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*zone.Gate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *zone.Gate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zone.Gate)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockGateRepositoryPort_Expecter) FindByID(ctx interface{}, id interface{}) *mock.Call {
	return _e.mock.On("FindByID", ctx, id)
}

// FindByToken provides a mock function with given fields: ctx, token
func (_m *MockGateRepositoryPort) FindByToken(ctx context.Context, token string) (*zone.Gate, error) {
	ret := _m.Called(ctx, token)
	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}
	var r0 *zone.Gate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*zone.Gate, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *zone.Gate); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zone.Gate)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockGateRepositoryPort_Expecter) FindByToken(ctx interface{}, token interface{}) *mock.Call {
	return _e.mock.On("FindByToken", ctx, token)
}

// FindByZoneID provides a mock function with given fields: ctx, filter, page, pageSize
func (_m *MockGateRepositoryPort) FindByZoneID(ctx context.Context, filter zone.ListGateFilter, page int, pageSize int) ([]zone.Gate, int64, error) {
	ret := _m.Called(ctx, filter, page, pageSize)
	if len(ret) == 0 {
		panic("no return value specified for FindByZoneID")
	}
	var r0 []zone.Gate
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, zone.ListGateFilter, int, int) ([]zone.Gate, int64, error)); ok {
		return rf(ctx, filter, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, zone.ListGateFilter, int, int) []zone.Gate); ok {
		r0 = rf(ctx, filter, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]zone.Gate)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, zone.ListGateFilter, int, int) int64); ok {
		r1 = rf(ctx, filter, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if rf, ok := ret.Get(2).(func(context.Context, zone.ListGateFilter, int, int) error); ok {
		r2 = rf(ctx, filter, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

func (_e *MockGateRepositoryPort_Expecter) FindByZoneID(ctx interface{}, filter interface{}, page interface{}, pageSize interface{}) *mock.Call {
	return _e.mock.On("FindByZoneID", ctx, filter, page, pageSize)
}

// Update provides a mock function with given fields: ctx, gate
func (_m *MockGateRepositoryPort) Update(ctx context.Context, gate *zone.Gate) error {
	ret := _m.Called(ctx, gate)
	if len(ret) == 0 {
		panic("no return value specified for Update")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *zone.Gate) error); ok {
		r0 = rf(ctx, gate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockGateRepositoryPort_Expecter) Update(ctx interface{}, gate interface{}) *mock.Call {
	return _e.mock.On("Update", ctx, gate)
}

// UpdateMode provides a mock function with given fields: ctx, id, mode
func (_m *MockGateRepositoryPort) UpdateMode(ctx context.Context, id uuid.UUID, mode types.GateMode) error {
	ret := _m.Called(ctx, id, mode)
	if len(ret) == 0 {
		panic("no return value specified for UpdateMode")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.GateMode) error); ok {
		r0 = rf(ctx, id, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockGateRepositoryPort_Expecter) UpdateMode(ctx interface{}, id interface{}, mode interface{}) *mock.Call {
	return _e.mock.On("UpdateMode", ctx, id, mode)
}

// UpdateTokenLastUsed provides a mock function with given fields: ctx, id
func (_m *MockGateRepositoryPort) UpdateTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for UpdateTokenLastUsed")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockGateRepositoryPort_Expecter) UpdateTokenLastUsed(ctx interface{}, id interface{}) *mock.Call {
	return _e.mock.On("UpdateTokenLastUsed", ctx, id)
}

// NewMockGateRepositoryPort creates a new instance of MockGateRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGateRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateRepositoryPort {
	mock := &MockGateRepositoryPort{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
