// Code generated by mockery. DO NOT EDIT.

package zone

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	zone "parkieee/internal/modules/zone"
)

// MockCapacityLogRepositoryPort is an autogenerated mock type for the CapacityLogRepositoryPort type
type MockCapacityLogRepositoryPort struct {
	mock.Mock
}

type MockCapacityLogRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCapacityLogRepositoryPort) EXPECT() *MockCapacityLogRepositoryPort_Expecter {
	return &MockCapacityLogRepositoryPort_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: ctx, log
func (_m *MockCapacityLogRepositoryPort) Append(ctx context.Context, log *zone.ZoneCapacityLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *zone.ZoneCapacityLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCapacityLogRepositoryPort_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockCapacityLogRepositoryPort_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - log *zone.ZoneCapacityLog
func (_e *MockCapacityLogRepositoryPort_Expecter) Append(ctx interface{}, log interface{}) *MockCapacityLogRepositoryPort_Append_Call {
	return &MockCapacityLogRepositoryPort_Append_Call{Call: _e.mock.On("Append", ctx, log)}
}

func (_c *MockCapacityLogRepositoryPort_Append_Call) Run(run func(ctx context.Context, log *zone.ZoneCapacityLog)) *MockCapacityLogRepositoryPort_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*zone.ZoneCapacityLog))
	})
	return _c
}

func (_c *MockCapacityLogRepositoryPort_Append_Call) Return(_a0 error) *MockCapacityLogRepositoryPort_Append_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCapacityLogRepositoryPort_Append_Call) RunAndReturn(run func(context.Context, *zone.ZoneCapacityLog) error) *MockCapacityLogRepositoryPort_Append_Call {
	_c.Call.Return(run)
	return _c
}

// LatestByZoneID provides a mock function with given fields: ctx, zoneID
func (_m *MockCapacityLogRepositoryPort) LatestByZoneID(ctx context.Context, zoneID uuid.UUID) (*zone.ZoneCapacityLog, error) {
	ret := _m.Called(ctx, zoneID)

	if len(ret) == 0 {
		panic("no return value specified for LatestByZoneID")
	}

	var r0 *zone.ZoneCapacityLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*zone.ZoneCapacityLog, error)); ok {
		return rf(ctx, zoneID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *zone.ZoneCapacityLog); ok {
		r0 = rf(ctx, zoneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zone.ZoneCapacityLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, zoneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCapacityLogRepositoryPort_LatestByZoneID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestByZoneID'
type MockCapacityLogRepositoryPort_LatestByZoneID_Call struct {
	*mock.Call
}

// LatestByZoneID is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID uuid.UUID
func (_e *MockCapacityLogRepositoryPort_Expecter) LatestByZoneID(ctx interface{}, zoneID interface{}) *MockCapacityLogRepositoryPort_LatestByZoneID_Call {
	return &MockCapacityLogRepositoryPort_LatestByZoneID_Call{Call: _e.mock.On("LatestByZoneID", ctx, zoneID)}
}

func (_c *MockCapacityLogRepositoryPort_LatestByZoneID_Call) Run(run func(ctx context.Context, zoneID uuid.UUID)) *MockCapacityLogRepositoryPort_LatestByZoneID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCapacityLogRepositoryPort_LatestByZoneID_Call) Return(_a0 *zone.ZoneCapacityLog, _a1 error) *MockCapacityLogRepositoryPort_LatestByZoneID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCapacityLogRepositoryPort_LatestByZoneID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*zone.ZoneCapacityLog, error)) *MockCapacityLogRepositoryPort_LatestByZoneID_Call {
	_c.Call.Return(run)
	return _c
}

// AllCapacities provides a mock function with given fields: ctx
func (_m *MockCapacityLogRepositoryPort) AllCapacities(ctx context.Context) ([]zone.ZoneCapacityResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllCapacities")
	}

	var r0 []zone.ZoneCapacityResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]zone.ZoneCapacityResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []zone.ZoneCapacityResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]zone.ZoneCapacityResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCapacityLogRepositoryPort_AllCapacities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllCapacities'
type MockCapacityLogRepositoryPort_AllCapacities_Call struct {
	*mock.Call
}

// AllCapacities is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCapacityLogRepositoryPort_Expecter) AllCapacities(ctx interface{}) *MockCapacityLogRepositoryPort_AllCapacities_Call {
	return &MockCapacityLogRepositoryPort_AllCapacities_Call{Call: _e.mock.On("AllCapacities", ctx)}
}

func (_c *MockCapacityLogRepositoryPort_AllCapacities_Call) Run(run func(ctx context.Context)) *MockCapacityLogRepositoryPort_AllCapacities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCapacityLogRepositoryPort_AllCapacities_Call) Return(_a0 []zone.ZoneCapacityResponse, _a1 error) *MockCapacityLogRepositoryPort_AllCapacities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCapacityLogRepositoryPort_AllCapacities_Call) RunAndReturn(run func(context.Context) ([]zone.ZoneCapacityResponse, error)) *MockCapacityLogRepositoryPort_AllCapacities_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCapacityLogRepositoryPort creates a new instance of MockCapacityLogRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCapacityLogRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCapacityLogRepositoryPort {
	mock := &MockCapacityLogRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
