// Code generated by mockery. DO NOT EDIT.

package fee

import (
	context "context"
	fee "parkieee/internal/modules/fee"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockHolidayRateRepositoryPort is an autogenerated mock type for the HolidayRateRepositoryPort type
type MockHolidayRateRepositoryPort struct {
	mock.Mock
}

type MockHolidayRateRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHolidayRateRepositoryPort) EXPECT() *MockHolidayRateRepositoryPort_Expecter {
	return &MockHolidayRateRepositoryPort_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, rate
func (_m *MockHolidayRateRepositoryPort) Create(ctx context.Context, rate *fee.HolidayRate) error {
	ret := _m.Called(ctx, rate)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fee.HolidayRate) error); ok {
		r0 = rf(ctx, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHolidayRateRepositoryPort_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHolidayRateRepositoryPort_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rate *fee.HolidayRate
func (_e *MockHolidayRateRepositoryPort_Expecter) Create(ctx interface{}, rate interface{}) *MockHolidayRateRepositoryPort_Create_Call {
	return &MockHolidayRateRepositoryPort_Create_Call{Call: _e.mock.On("Create", ctx, rate)}
}

func (_c *MockHolidayRateRepositoryPort_Create_Call) Run(run func(ctx context.Context, rate *fee.HolidayRate)) *MockHolidayRateRepositoryPort_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*fee.HolidayRate))
	})
	return _c
}

func (_c *MockHolidayRateRepositoryPort_Create_Call) Return(_a0 error) *MockHolidayRateRepositoryPort_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHolidayRateRepositoryPort_Create_Call) RunAndReturn(run func(context.Context, *fee.HolidayRate) error) *MockHolidayRateRepositoryPort_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockHolidayRateRepositoryPort) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHolidayRateRepositoryPort_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHolidayRateRepositoryPort_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockHolidayRateRepositoryPort_Expecter) Delete(ctx interface{}, id interface{}) *MockHolidayRateRepositoryPort_Delete_Call {
	return &MockHolidayRateRepositoryPort_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockHolidayRateRepositoryPort_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockHolidayRateRepositoryPort_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockHolidayRateRepositoryPort_Delete_Call) Return(_a0 error) *MockHolidayRateRepositoryPort_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHolidayRateRepositoryPort_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockHolidayRateRepositoryPort_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveForDate provides a mock function with given fields: ctx, date, zoneID, vehicleTypeID
func (_m *MockHolidayRateRepositoryPort) FindActiveForDate(ctx context.Context, date time.Time, zoneID *uuid.UUID, vehicleTypeID *uuid.UUID) ([]fee.HolidayRate, error) {
	ret := _m.Called(ctx, date, zoneID, vehicleTypeID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveForDate")
	}

	var r0 []fee.HolidayRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, *uuid.UUID, *uuid.UUID) ([]fee.HolidayRate, error)); ok {
		return rf(ctx, date, zoneID, vehicleTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, *uuid.UUID, *uuid.UUID) []fee.HolidayRate); ok {
		r0 = rf(ctx, date, zoneID, vehicleTypeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fee.HolidayRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, *uuid.UUID, *uuid.UUID) error); ok {
		r1 = rf(ctx, date, zoneID, vehicleTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHolidayRateRepositoryPort_FindActiveForDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveForDate'
type MockHolidayRateRepositoryPort_FindActiveForDate_Call struct {
	*mock.Call
}

// FindActiveForDate is a helper method to define mock.On call
//   - ctx context.Context
//   - date time.Time
//   - zoneID *uuid.UUID
//   - vehicleTypeID *uuid.UUID
func (_e *MockHolidayRateRepositoryPort_Expecter) FindActiveForDate(ctx interface{}, date interface{}, zoneID interface{}, vehicleTypeID interface{}) *MockHolidayRateRepositoryPort_FindActiveForDate_Call {
	return &MockHolidayRateRepositoryPort_FindActiveForDate_Call{Call: _e.mock.On("FindActiveForDate", ctx, date, zoneID, vehicleTypeID)}
}

func (_c *MockHolidayRateRepositoryPort_FindActiveForDate_Call) Run(run func(ctx context.Context, date time.Time, zoneID *uuid.UUID, vehicleTypeID *uuid.UUID)) *MockHolidayRateRepositoryPort_FindActiveForDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(*uuid.UUID), args[3].(*uuid.UUID))
	})
	return _c
}

func (_c *MockHolidayRateRepositoryPort_FindActiveForDate_Call) Return(_a0 []fee.HolidayRate, _a1 error) *MockHolidayRateRepositoryPort_FindActiveForDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHolidayRateRepositoryPort_FindActiveForDate_Call) RunAndReturn(run func(context.Context, time.Time, *uuid.UUID, *uuid.UUID) ([]fee.HolidayRate, error)) *MockHolidayRateRepositoryPort_FindActiveForDate_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, page, pageSize
func (_m *MockHolidayRateRepositoryPort) FindAll(ctx context.Context, page int, pageSize int) ([]fee.HolidayRate, int64, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []fee.HolidayRate
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]fee.HolidayRate, int64, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []fee.HolidayRate); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fee.HolidayRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockHolidayRateRepositoryPort_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockHolidayRateRepositoryPort_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockHolidayRateRepositoryPort_Expecter) FindAll(ctx interface{}, page interface{}, pageSize interface{}) *MockHolidayRateRepositoryPort_FindAll_Call {
	return &MockHolidayRateRepositoryPort_FindAll_Call{Call: _e.mock.On("FindAll", ctx, page, pageSize)}
}

func (_c *MockHolidayRateRepositoryPort_FindAll_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockHolidayRateRepositoryPort_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockHolidayRateRepositoryPort_FindAll_Call) Return(_a0 []fee.HolidayRate, _a1 int64, _a2 error) *MockHolidayRateRepositoryPort_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockHolidayRateRepositoryPort_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]fee.HolidayRate, int64, error)) *MockHolidayRateRepositoryPort_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockHolidayRateRepositoryPort) FindByID(ctx context.Context, id uuid.UUID) (*fee.HolidayRate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *fee.HolidayRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*fee.HolidayRate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *fee.HolidayRate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fee.HolidayRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHolidayRateRepositoryPort_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockHolidayRateRepositoryPort_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockHolidayRateRepositoryPort_Expecter) FindByID(ctx interface{}, id interface{}) *MockHolidayRateRepositoryPort_FindByID_Call {
	return &MockHolidayRateRepositoryPort_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockHolidayRateRepositoryPort_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockHolidayRateRepositoryPort_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockHolidayRateRepositoryPort_FindByID_Call) Return(_a0 *fee.HolidayRate, _a1 error) *MockHolidayRateRepositoryPort_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHolidayRateRepositoryPort_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*fee.HolidayRate, error)) *MockHolidayRateRepositoryPort_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, rate
func (_m *MockHolidayRateRepositoryPort) Update(ctx context.Context, rate *fee.HolidayRate) error {
	ret := _m.Called(ctx, rate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fee.HolidayRate) error); ok {
		r0 = rf(ctx, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHolidayRateRepositoryPort_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockHolidayRateRepositoryPort_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rate *fee.HolidayRate
func (_e *MockHolidayRateRepositoryPort_Expecter) Update(ctx interface{}, rate interface{}) *MockHolidayRateRepositoryPort_Update_Call {
	return &MockHolidayRateRepositoryPort_Update_Call{Call: _e.mock.On("Update", ctx, rate)}
}

func (_c *MockHolidayRateRepositoryPort_Update_Call) Run(run func(ctx context.Context, rate *fee.HolidayRate)) *MockHolidayRateRepositoryPort_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*fee.HolidayRate))
	})
	return _c
}

func (_c *MockHolidayRateRepositoryPort_Update_Call) Return(_a0 error) *MockHolidayRateRepositoryPort_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHolidayRateRepositoryPort_Update_Call) RunAndReturn(run func(context.Context, *fee.HolidayRate) error) *MockHolidayRateRepositoryPort_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHolidayRateRepositoryPort creates a new instance of MockHolidayRateRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHolidayRateRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHolidayRateRepositoryPort {
	mock := &MockHolidayRateRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
