// Code generated by mockery. DO NOT EDIT.

package fee

import (
	context "context"
	fee "parkieee/internal/modules/fee"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockFeeConfigRepositoryPort is an autogenerated mock type for the FeeConfigRepositoryPort type
type MockFeeConfigRepositoryPort struct {
	mock.Mock
}

type MockFeeConfigRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeeConfigRepositoryPort) EXPECT() *MockFeeConfigRepositoryPort_Expecter {
	return &MockFeeConfigRepositoryPort_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, config
func (_m *MockFeeConfigRepositoryPort) Create(ctx context.Context, config *fee.FeeConfig) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fee.FeeConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeeConfigRepositoryPort_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFeeConfigRepositoryPort_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - config *fee.FeeConfig
func (_e *MockFeeConfigRepositoryPort_Expecter) Create(ctx interface{}, config interface{}) *MockFeeConfigRepositoryPort_Create_Call {
	return &MockFeeConfigRepositoryPort_Create_Call{Call: _e.mock.On("Create", ctx, config)}
}

func (_c *MockFeeConfigRepositoryPort_Create_Call) Run(run func(ctx context.Context, config *fee.FeeConfig)) *MockFeeConfigRepositoryPort_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*fee.FeeConfig))
	})
	return _c
}

func (_c *MockFeeConfigRepositoryPort_Create_Call) Return(_a0 error) *MockFeeConfigRepositoryPort_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeeConfigRepositoryPort_Create_Call) RunAndReturn(run func(context.Context, *fee.FeeConfig) error) *MockFeeConfigRepositoryPort_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function with given fields: ctx, id
func (_m *MockFeeConfigRepositoryPort) Deactivate(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeeConfigRepositoryPort_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockFeeConfigRepositoryPort_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFeeConfigRepositoryPort_Expecter) Deactivate(ctx interface{}, id interface{}) *MockFeeConfigRepositoryPort_Deactivate_Call {
	return &MockFeeConfigRepositoryPort_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, id)}
}

func (_c *MockFeeConfigRepositoryPort_Deactivate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFeeConfigRepositoryPort_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFeeConfigRepositoryPort_Deactivate_Call) Return(_a0 error) *MockFeeConfigRepositoryPort_Deactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeeConfigRepositoryPort_Deactivate_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockFeeConfigRepositoryPort_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByZoneAndVehicle provides a mock function with given fields: ctx, zoneID, vehicleTypeID
func (_m *MockFeeConfigRepositoryPort) FindActiveByZoneAndVehicle(ctx context.Context, zoneID uuid.UUID, vehicleTypeID uuid.UUID) (*fee.FeeConfig, error) {
	ret := _m.Called(ctx, zoneID, vehicleTypeID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByZoneAndVehicle")
	}

	var r0 *fee.FeeConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*fee.FeeConfig, error)); ok {
		return rf(ctx, zoneID, vehicleTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *fee.FeeConfig); ok {
		r0 = rf(ctx, zoneID, vehicleTypeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fee.FeeConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, zoneID, vehicleTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFeeConfigRepositoryPort_FindActiveByZoneAndVehicle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByZoneAndVehicle'
type MockFeeConfigRepositoryPort_FindActiveByZoneAndVehicle_Call struct {
	*mock.Call
}

// FindActiveByZoneAndVehicle is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID uuid.UUID
//   - vehicleTypeID uuid.UUID
func (_e *MockFeeConfigRepositoryPort_Expecter) FindActiveByZoneAndVehicle(ctx interface{}, zoneID interface{}, vehicleTypeID interface{}) *MockFeeConfigRepositoryPort_FindActiveByZoneAndVehicle_Call {
	return &MockFeeConfigRepositoryPort_FindActiveByZoneAndVehicle_Call{Call: _e.mock.On("FindActiveByZoneAndVehicle", ctx, zoneID, vehicleTypeID)}
}

func (_c *MockFeeConfigRepositoryPort_FindActiveByZoneAndVehicle_Call) Run(run func(ctx context.Context, zoneID uuid.UUID, vehicleTypeID uuid.UUID)) *MockFeeConfigRepositoryPort_FindActiveByZoneAndVehicle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockFeeConfigRepositoryPort_FindActiveByZoneAndVehicle_Call) Return(_a0 *fee.FeeConfig, _a1 error) *MockFeeConfigRepositoryPort_FindActiveByZoneAndVehicle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFeeConfigRepositoryPort_FindActiveByZoneAndVehicle_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*fee.FeeConfig, error)) *MockFeeConfigRepositoryPort_FindActiveByZoneAndVehicle_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, filter, page, pageSize
func (_m *MockFeeConfigRepositoryPort) FindAll(ctx context.Context, filter fee.ListFeeConfigFilter, page int, pageSize int) ([]fee.FeeConfig, int64, error) {
	ret := _m.Called(ctx, filter, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []fee.FeeConfig
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, fee.ListFeeConfigFilter, int, int) ([]fee.FeeConfig, int64, error)); ok {
		return rf(ctx, filter, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, fee.ListFeeConfigFilter, int, int) []fee.FeeConfig); ok {
		r0 = rf(ctx, filter, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fee.FeeConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, fee.ListFeeConfigFilter, int, int) int64); ok {
		r1 = rf(ctx, filter, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, fee.ListFeeConfigFilter, int, int) error); ok {
		r2 = rf(ctx, filter, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFeeConfigRepositoryPort_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockFeeConfigRepositoryPort_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter fee.ListFeeConfigFilter
//   - page int
//   - pageSize int
func (_e *MockFeeConfigRepositoryPort_Expecter) FindAll(ctx interface{}, filter interface{}, page interface{}, pageSize interface{}) *MockFeeConfigRepositoryPort_FindAll_Call {
	return &MockFeeConfigRepositoryPort_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter, page, pageSize)}
}

func (_c *MockFeeConfigRepositoryPort_FindAll_Call) Run(run func(ctx context.Context, filter fee.ListFeeConfigFilter, page int, pageSize int)) *MockFeeConfigRepositoryPort_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(fee.ListFeeConfigFilter), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockFeeConfigRepositoryPort_FindAll_Call) Return(_a0 []fee.FeeConfig, _a1 int64, _a2 error) *MockFeeConfigRepositoryPort_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockFeeConfigRepositoryPort_FindAll_Call) RunAndReturn(run func(context.Context, fee.ListFeeConfigFilter, int, int) ([]fee.FeeConfig, int64, error)) *MockFeeConfigRepositoryPort_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockFeeConfigRepositoryPort) FindByID(ctx context.Context, id uuid.UUID) (*fee.FeeConfig, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *fee.FeeConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*fee.FeeConfig, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *fee.FeeConfig); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fee.FeeConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFeeConfigRepositoryPort_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockFeeConfigRepositoryPort_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFeeConfigRepositoryPort_Expecter) FindByID(ctx interface{}, id interface{}) *MockFeeConfigRepositoryPort_FindByID_Call {
	return &MockFeeConfigRepositoryPort_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockFeeConfigRepositoryPort_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFeeConfigRepositoryPort_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFeeConfigRepositoryPort_FindByID_Call) Return(_a0 *fee.FeeConfig, _a1 error) *MockFeeConfigRepositoryPort_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFeeConfigRepositoryPort_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*fee.FeeConfig, error)) *MockFeeConfigRepositoryPort_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFeeConfigRepositoryPort creates a new instance of MockFeeConfigRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeeConfigRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeeConfigRepositoryPort {
	mock := &MockFeeConfigRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
