// Code generated by mockery. DO NOT EDIT.

package fee

import (
	context "context"
	fee "parkieee/internal/modules/fee"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockFeeTierRepositoryPort is an autogenerated mock type for the FeeTierRepositoryPort type
type MockFeeTierRepositoryPort struct {
	mock.Mock
}

type MockFeeTierRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeeTierRepositoryPort) EXPECT() *MockFeeTierRepositoryPort_Expecter {
	return &MockFeeTierRepositoryPort_Expecter{mock: &_m.Mock}
}

// CreateBatch provides a mock function with given fields: ctx, tiers
func (_m *MockFeeTierRepositoryPort) CreateBatch(ctx context.Context, tiers []fee.FeeTier) error {
	ret := _m.Called(ctx, tiers)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []fee.FeeTier) error); ok {
		r0 = rf(ctx, tiers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeeTierRepositoryPort_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockFeeTierRepositoryPort_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - tiers []fee.FeeTier
func (_e *MockFeeTierRepositoryPort_Expecter) CreateBatch(ctx interface{}, tiers interface{}) *MockFeeTierRepositoryPort_CreateBatch_Call {
	return &MockFeeTierRepositoryPort_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, tiers)}
}

func (_c *MockFeeTierRepositoryPort_CreateBatch_Call) Run(run func(ctx context.Context, tiers []fee.FeeTier)) *MockFeeTierRepositoryPort_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]fee.FeeTier))
	})
	return _c
}

func (_c *MockFeeTierRepositoryPort_CreateBatch_Call) Return(_a0 error) *MockFeeTierRepositoryPort_CreateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeeTierRepositoryPort_CreateBatch_Call) RunAndReturn(run func(context.Context, []fee.FeeTier) error) *MockFeeTierRepositoryPort_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByFeeConfigID provides a mock function with given fields: ctx, feeConfigID
func (_m *MockFeeTierRepositoryPort) DeleteByFeeConfigID(ctx context.Context, feeConfigID uuid.UUID) error {
	ret := _m.Called(ctx, feeConfigID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByFeeConfigID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, feeConfigID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeeTierRepositoryPort_DeleteByFeeConfigID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByFeeConfigID'
type MockFeeTierRepositoryPort_DeleteByFeeConfigID_Call struct {
	*mock.Call
}

// DeleteByFeeConfigID is a helper method to define mock.On call
//   - ctx context.Context
//   - feeConfigID uuid.UUID
func (_e *MockFeeTierRepositoryPort_Expecter) DeleteByFeeConfigID(ctx interface{}, feeConfigID interface{}) *MockFeeTierRepositoryPort_DeleteByFeeConfigID_Call {
	return &MockFeeTierRepositoryPort_DeleteByFeeConfigID_Call{Call: _e.mock.On("DeleteByFeeConfigID", ctx, feeConfigID)}
}

func (_c *MockFeeTierRepositoryPort_DeleteByFeeConfigID_Call) Run(run func(ctx context.Context, feeConfigID uuid.UUID)) *MockFeeTierRepositoryPort_DeleteByFeeConfigID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFeeTierRepositoryPort_DeleteByFeeConfigID_Call) Return(_a0 error) *MockFeeTierRepositoryPort_DeleteByFeeConfigID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeeTierRepositoryPort_DeleteByFeeConfigID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockFeeTierRepositoryPort_DeleteByFeeConfigID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFeeConfigID provides a mock function with given fields: ctx, feeConfigID
func (_m *MockFeeTierRepositoryPort) FindByFeeConfigID(ctx context.Context, feeConfigID uuid.UUID) ([]fee.FeeTier, error) {
	ret := _m.Called(ctx, feeConfigID)

	if len(ret) == 0 {
		panic("no return value specified for FindByFeeConfigID")
	}

	var r0 []fee.FeeTier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]fee.FeeTier, error)); ok {
		return rf(ctx, feeConfigID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []fee.FeeTier); ok {
		r0 = rf(ctx, feeConfigID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fee.FeeTier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, feeConfigID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFeeTierRepositoryPort_FindByFeeConfigID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFeeConfigID'
type MockFeeTierRepositoryPort_FindByFeeConfigID_Call struct {
	*mock.Call
}

// FindByFeeConfigID is a helper method to define mock.On call
//   - ctx context.Context
//   - feeConfigID uuid.UUID
func (_e *MockFeeTierRepositoryPort_Expecter) FindByFeeConfigID(ctx interface{}, feeConfigID interface{}) *MockFeeTierRepositoryPort_FindByFeeConfigID_Call {
	return &MockFeeTierRepositoryPort_FindByFeeConfigID_Call{Call: _e.mock.On("FindByFeeConfigID", ctx, feeConfigID)}
}

func (_c *MockFeeTierRepositoryPort_FindByFeeConfigID_Call) Run(run func(ctx context.Context, feeConfigID uuid.UUID)) *MockFeeTierRepositoryPort_FindByFeeConfigID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFeeTierRepositoryPort_FindByFeeConfigID_Call) Return(_a0 []fee.FeeTier, _a1 error) *MockFeeTierRepositoryPort_FindByFeeConfigID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFeeTierRepositoryPort_FindByFeeConfigID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]fee.FeeTier, error)) *MockFeeTierRepositoryPort_FindByFeeConfigID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFeeTierRepositoryPort creates a new instance of MockFeeTierRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeeTierRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeeTierRepositoryPort {
	mock := &MockFeeTierRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
