// Code generated by mockery. DO NOT EDIT.

package transaction

import (
	context "context"
	ocr "parkieee/internal/modules/ocr"

	mock "github.com/stretchr/testify/mock"

	transaction "parkieee/internal/modules/transaction"

	types "parkieee/pkg/types"

	uuid "github.com/google/uuid"
)

// MockServicePort is an autogenerated mock type for the ServicePort type
type MockServicePort struct {
	mock.Mock
}

type MockServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicePort) EXPECT() *MockServicePort_Expecter {
	return &MockServicePort_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, id, reason, operatorID
func (_m *MockServicePort) Cancel(ctx context.Context, id uuid.UUID, reason string, operatorID uuid.UUID) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, id, reason, operatorID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (*transaction.Transaction, error)); ok {
		return rf(ctx, id, reason, operatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) *transaction.Transaction); ok {
		r0 = rf(ctx, id, reason, operatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, id, reason, operatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicePort_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockServicePort_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - reason string
//   - operatorID uuid.UUID
func (_e *MockServicePort_Expecter) Cancel(ctx interface{}, id interface{}, reason interface{}, operatorID interface{}) *MockServicePort_Cancel_Call {
	return &MockServicePort_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id, reason, operatorID)}
}

func (_c *MockServicePort_Cancel_Call) Run(run func(ctx context.Context, id uuid.UUID, reason string, operatorID uuid.UUID)) *MockServicePort_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockServicePort_Cancel_Call) Return(_a0 *transaction.Transaction, _a1 error) *MockServicePort_Cancel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicePort_Cancel_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) (*transaction.Transaction, error)) *MockServicePort_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function with given fields: ctx, code
func (_m *MockServicePort) GetByCode(ctx context.Context, code string) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*transaction.Transaction, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *transaction.Transaction); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicePort_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type MockServicePort_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockServicePort_Expecter) GetByCode(ctx interface{}, code interface{}) *MockServicePort_GetByCode_Call {
	return &MockServicePort_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *MockServicePort_GetByCode_Call) Run(run func(ctx context.Context, code string)) *MockServicePort_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServicePort_GetByCode_Call) Return(_a0 *transaction.Transaction, _a1 error) *MockServicePort_GetByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicePort_GetByCode_Call) RunAndReturn(run func(context.Context, string) (*transaction.Transaction, error)) *MockServicePort_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogs provides a mock function with given fields: ctx, txID
func (_m *MockServicePort) GetLogs(ctx context.Context, txID uuid.UUID) ([]transaction.TransactionLog, error) {
	ret := _m.Called(ctx, txID)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []transaction.TransactionLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]transaction.TransactionLog, error)); ok {
		return rf(ctx, txID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []transaction.TransactionLog); ok {
		r0 = rf(ctx, txID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.TransactionLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, txID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicePort_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type MockServicePort_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - txID uuid.UUID
func (_e *MockServicePort_Expecter) GetLogs(ctx interface{}, txID interface{}) *MockServicePort_GetLogs_Call {
	return &MockServicePort_GetLogs_Call{Call: _e.mock.On("GetLogs", ctx, txID)}
}

func (_c *MockServicePort_GetLogs_Call) Run(run func(ctx context.Context, txID uuid.UUID)) *MockServicePort_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockServicePort_GetLogs_Call) Return(_a0 []transaction.TransactionLog, _a1 error) *MockServicePort_GetLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicePort_GetLogs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]transaction.TransactionLog, error)) *MockServicePort_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetOpenByRFIDUID provides a mock function with given fields: ctx, uid
func (_m *MockServicePort) GetOpenByRFIDUID(ctx context.Context, uid string) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenByRFIDUID")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*transaction.Transaction, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *transaction.Transaction); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicePort_GetOpenByRFIDUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenByRFIDUID'
type MockServicePort_GetOpenByRFIDUID_Call struct {
	*mock.Call
}

// GetOpenByRFIDUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockServicePort_Expecter) GetOpenByRFIDUID(ctx interface{}, uid interface{}) *MockServicePort_GetOpenByRFIDUID_Call {
	return &MockServicePort_GetOpenByRFIDUID_Call{Call: _e.mock.On("GetOpenByRFIDUID", ctx, uid)}
}

func (_c *MockServicePort_GetOpenByRFIDUID_Call) Run(run func(ctx context.Context, uid string)) *MockServicePort_GetOpenByRFIDUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServicePort_GetOpenByRFIDUID_Call) Return(_a0 *transaction.Transaction, _a1 error) *MockServicePort_GetOpenByRFIDUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicePort_GetOpenByRFIDUID_Call) RunAndReturn(run func(context.Context, string) (*transaction.Transaction, error)) *MockServicePort_GetOpenByRFIDUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransaction provides a mock function with given fields: ctx, id
func (_m *MockServicePort) GetTransaction(ctx context.Context, id uuid.UUID) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*transaction.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *transaction.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicePort_GetTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransaction'
type MockServicePort_GetTransaction_Call struct {
	*mock.Call
}

// GetTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockServicePort_Expecter) GetTransaction(ctx interface{}, id interface{}) *MockServicePort_GetTransaction_Call {
	return &MockServicePort_GetTransaction_Call{Call: _e.mock.On("GetTransaction", ctx, id)}
}

func (_c *MockServicePort_GetTransaction_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockServicePort_GetTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockServicePort_GetTransaction_Call) Return(_a0 *transaction.Transaction, _a1 error) *MockServicePort_GetTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicePort_GetTransaction_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*transaction.Transaction, error)) *MockServicePort_GetTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransactions provides a mock function with given fields: ctx, filter, page, pageSize
func (_m *MockServicePort) ListTransactions(ctx context.Context, filter transaction.ListFilter, page int, pageSize int) ([]transaction.Transaction, int64, error) {
	ret := _m.Called(ctx, filter, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactions")
	}

	var r0 []transaction.Transaction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, transaction.ListFilter, int, int) ([]transaction.Transaction, int64, error)); ok {
		return rf(ctx, filter, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transaction.ListFilter, int, int) []transaction.Transaction); ok {
		r0 = rf(ctx, filter, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, transaction.ListFilter, int, int) int64); ok {
		r1 = rf(ctx, filter, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, transaction.ListFilter, int, int) error); ok {
		r2 = rf(ctx, filter, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockServicePort_ListTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactions'
type MockServicePort_ListTransactions_Call struct {
	*mock.Call
}

// ListTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - filter transaction.ListFilter
//   - page int
//   - pageSize int
func (_e *MockServicePort_Expecter) ListTransactions(ctx interface{}, filter interface{}, page interface{}, pageSize interface{}) *MockServicePort_ListTransactions_Call {
	return &MockServicePort_ListTransactions_Call{Call: _e.mock.On("ListTransactions", ctx, filter, page, pageSize)}
}

func (_c *MockServicePort_ListTransactions_Call) Run(run func(ctx context.Context, filter transaction.ListFilter, page int, pageSize int)) *MockServicePort_ListTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transaction.ListFilter), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockServicePort_ListTransactions_Call) Return(_a0 []transaction.Transaction, _a1 int64, _a2 error) *MockServicePort_ListTransactions_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockServicePort_ListTransactions_Call) RunAndReturn(run func(context.Context, transaction.ListFilter, int, int) ([]transaction.Transaction, int64, error)) *MockServicePort_ListTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// LoadOCRSummary provides a mock function with given fields: ctx, txID
func (_m *MockServicePort) LoadOCRSummary(ctx context.Context, txID uuid.UUID) []ocr.OCRResultWithJob {
	ret := _m.Called(ctx, txID)

	if len(ret) == 0 {
		panic("no return value specified for LoadOCRSummary")
	}

	var r0 []ocr.OCRResultWithJob
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []ocr.OCRResultWithJob); ok {
		r0 = rf(ctx, txID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ocr.OCRResultWithJob)
		}
	}

	return r0
}

// MockServicePort_LoadOCRSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadOCRSummary'
type MockServicePort_LoadOCRSummary_Call struct {
	*mock.Call
}

// LoadOCRSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - txID uuid.UUID
func (_e *MockServicePort_Expecter) LoadOCRSummary(ctx interface{}, txID interface{}) *MockServicePort_LoadOCRSummary_Call {
	return &MockServicePort_LoadOCRSummary_Call{Call: _e.mock.On("LoadOCRSummary", ctx, txID)}
}

func (_c *MockServicePort_LoadOCRSummary_Call) Run(run func(ctx context.Context, txID uuid.UUID)) *MockServicePort_LoadOCRSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockServicePort_LoadOCRSummary_Call) Return(_a0 []ocr.OCRResultWithJob) *MockServicePort_LoadOCRSummary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServicePort_LoadOCRSummary_Call) RunAndReturn(run func(context.Context, uuid.UUID) []ocr.OCRResultWithJob) *MockServicePort_LoadOCRSummary_Call {
	_c.Call.Return(run)
	return _c
}

// MarkExited provides a mock function with given fields: ctx, txID, triggeredBy
func (_m *MockServicePort) MarkExited(ctx context.Context, txID uuid.UUID, triggeredBy types.TriggeredBy) error {
	ret := _m.Called(ctx, txID, triggeredBy)

	if len(ret) == 0 {
		panic("no return value specified for MarkExited")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.TriggeredBy) error); ok {
		r0 = rf(ctx, txID, triggeredBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServicePort_MarkExited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkExited'
type MockServicePort_MarkExited_Call struct {
	*mock.Call
}

// MarkExited is a helper method to define mock.On call
//   - ctx context.Context
//   - txID uuid.UUID
//   - triggeredBy types.TriggeredBy
func (_e *MockServicePort_Expecter) MarkExited(ctx interface{}, txID interface{}, triggeredBy interface{}) *MockServicePort_MarkExited_Call {
	return &MockServicePort_MarkExited_Call{Call: _e.mock.On("MarkExited", ctx, txID, triggeredBy)}
}

func (_c *MockServicePort_MarkExited_Call) Run(run func(ctx context.Context, txID uuid.UUID, triggeredBy types.TriggeredBy)) *MockServicePort_MarkExited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(types.TriggeredBy))
	})
	return _c
}

func (_c *MockServicePort_MarkExited_Call) Return(_a0 error) *MockServicePort_MarkExited_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServicePort_MarkExited_Call) RunAndReturn(run func(context.Context, uuid.UUID, types.TriggeredBy) error) *MockServicePort_MarkExited_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaid provides a mock function with given fields: ctx, txID, triggeredBy, handledByUserID
func (_m *MockServicePort) MarkPaid(ctx context.Context, txID uuid.UUID, triggeredBy types.TriggeredBy, handledByUserID *uuid.UUID) error {
	ret := _m.Called(ctx, txID, triggeredBy, handledByUserID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.TriggeredBy, *uuid.UUID) error); ok {
		r0 = rf(ctx, txID, triggeredBy, handledByUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServicePort_MarkPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaid'
type MockServicePort_MarkPaid_Call struct {
	*mock.Call
}

// MarkPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - txID uuid.UUID
//   - triggeredBy types.TriggeredBy
//   - handledByUserID *uuid.UUID
func (_e *MockServicePort_Expecter) MarkPaid(ctx interface{}, txID interface{}, triggeredBy interface{}, handledByUserID interface{}) *MockServicePort_MarkPaid_Call {
	return &MockServicePort_MarkPaid_Call{Call: _e.mock.On("MarkPaid", ctx, txID, triggeredBy, handledByUserID)}
}

func (_c *MockServicePort_MarkPaid_Call) Run(run func(ctx context.Context, txID uuid.UUID, triggeredBy types.TriggeredBy, handledByUserID *uuid.UUID)) *MockServicePort_MarkPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(types.TriggeredBy), args[3].(*uuid.UUID))
	})
	return _c
}

func (_c *MockServicePort_MarkPaid_Call) Return(_a0 error) *MockServicePort_MarkPaid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServicePort_MarkPaid_Call) RunAndReturn(run func(context.Context, uuid.UUID, types.TriggeredBy, *uuid.UUID) error) *MockServicePort_MarkPaid_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaidAndExited provides a mock function with given fields: ctx, txID, triggeredBy, handledByUserID
func (_m *MockServicePort) MarkPaidAndExited(ctx context.Context, txID uuid.UUID, triggeredBy types.TriggeredBy, handledByUserID *uuid.UUID) error {
	ret := _m.Called(ctx, txID, triggeredBy, handledByUserID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaidAndExited")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.TriggeredBy, *uuid.UUID) error); ok {
		r0 = rf(ctx, txID, triggeredBy, handledByUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServicePort_MarkPaidAndExited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaidAndExited'
type MockServicePort_MarkPaidAndExited_Call struct {
	*mock.Call
}

// MarkPaidAndExited is a helper method to define mock.On call
//   - ctx context.Context
//   - txID uuid.UUID
//   - triggeredBy types.TriggeredBy
//   - handledByUserID *uuid.UUID
func (_e *MockServicePort_Expecter) MarkPaidAndExited(ctx interface{}, txID interface{}, triggeredBy interface{}, handledByUserID interface{}) *MockServicePort_MarkPaidAndExited_Call {
	return &MockServicePort_MarkPaidAndExited_Call{Call: _e.mock.On("MarkPaidAndExited", ctx, txID, triggeredBy, handledByUserID)}
}

func (_c *MockServicePort_MarkPaidAndExited_Call) Run(run func(ctx context.Context, txID uuid.UUID, triggeredBy types.TriggeredBy, handledByUserID *uuid.UUID)) *MockServicePort_MarkPaidAndExited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(types.TriggeredBy), args[3].(*uuid.UUID))
	})
	return _c
}

func (_c *MockServicePort_MarkPaidAndExited_Call) Return(_a0 error) *MockServicePort_MarkPaidAndExited_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServicePort_MarkPaidAndExited_Call) RunAndReturn(run func(context.Context, uuid.UUID, types.TriggeredBy, *uuid.UUID) error) *MockServicePort_MarkPaidAndExited_Call {
	_c.Call.Return(run)
	return _c
}

// RecordEntry provides a mock function with given fields: ctx, req, operatorID
func (_m *MockServicePort) RecordEntry(ctx context.Context, req transaction.RecordEntryRequest, operatorID uuid.UUID) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, req, operatorID)

	if len(ret) == 0 {
		panic("no return value specified for RecordEntry")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, transaction.RecordEntryRequest, uuid.UUID) (*transaction.Transaction, error)); ok {
		return rf(ctx, req, operatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transaction.RecordEntryRequest, uuid.UUID) *transaction.Transaction); ok {
		r0 = rf(ctx, req, operatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, transaction.RecordEntryRequest, uuid.UUID) error); ok {
		r1 = rf(ctx, req, operatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicePort_RecordEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordEntry'
type MockServicePort_RecordEntry_Call struct {
	*mock.Call
}

// RecordEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - req transaction.RecordEntryRequest
//   - operatorID uuid.UUID
func (_e *MockServicePort_Expecter) RecordEntry(ctx interface{}, req interface{}, operatorID interface{}) *MockServicePort_RecordEntry_Call {
	return &MockServicePort_RecordEntry_Call{Call: _e.mock.On("RecordEntry", ctx, req, operatorID)}
}

func (_c *MockServicePort_RecordEntry_Call) Run(run func(ctx context.Context, req transaction.RecordEntryRequest, operatorID uuid.UUID)) *MockServicePort_RecordEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transaction.RecordEntryRequest), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockServicePort_RecordEntry_Call) Return(_a0 *transaction.Transaction, _a1 error) *MockServicePort_RecordEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicePort_RecordEntry_Call) RunAndReturn(run func(context.Context, transaction.RecordEntryRequest, uuid.UUID) (*transaction.Transaction, error)) *MockServicePort_RecordEntry_Call {
	_c.Call.Return(run)
	return _c
}

// RecordExit provides a mock function with given fields: ctx, id, req, operatorID
func (_m *MockServicePort) RecordExit(ctx context.Context, id uuid.UUID, req transaction.RecordExitRequest, operatorID uuid.UUID) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, id, req, operatorID)

	if len(ret) == 0 {
		panic("no return value specified for RecordExit")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, transaction.RecordExitRequest, uuid.UUID) (*transaction.Transaction, error)); ok {
		return rf(ctx, id, req, operatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, transaction.RecordExitRequest, uuid.UUID) *transaction.Transaction); ok {
		r0 = rf(ctx, id, req, operatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, transaction.RecordExitRequest, uuid.UUID) error); ok {
		r1 = rf(ctx, id, req, operatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicePort_RecordExit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordExit'
type MockServicePort_RecordExit_Call struct {
	*mock.Call
}

// RecordExit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - req transaction.RecordExitRequest
//   - operatorID uuid.UUID
func (_e *MockServicePort_Expecter) RecordExit(ctx interface{}, id interface{}, req interface{}, operatorID interface{}) *MockServicePort_RecordExit_Call {
	return &MockServicePort_RecordExit_Call{Call: _e.mock.On("RecordExit", ctx, id, req, operatorID)}
}

func (_c *MockServicePort_RecordExit_Call) Run(run func(ctx context.Context, id uuid.UUID, req transaction.RecordExitRequest, operatorID uuid.UUID)) *MockServicePort_RecordExit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(transaction.RecordExitRequest), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockServicePort_RecordExit_Call) Return(_a0 *transaction.Transaction, _a1 error) *MockServicePort_RecordExit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicePort_RecordExit_Call) RunAndReturn(run func(context.Context, uuid.UUID, transaction.RecordExitRequest, uuid.UUID) (*transaction.Transaction, error)) *MockServicePort_RecordExit_Call {
	_c.Call.Return(run)
	return _c
}

// SimulateEntryTime provides a mock function with given fields: ctx, id, minutesAgo
func (_m *MockServicePort) SimulateEntryTime(ctx context.Context, id uuid.UUID, minutesAgo int) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, id, minutesAgo)

	if len(ret) == 0 {
		panic("no return value specified for SimulateEntryTime")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*transaction.Transaction, error)); ok {
		return rf(ctx, id, minutesAgo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *transaction.Transaction); ok {
		r0 = rf(ctx, id, minutesAgo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, id, minutesAgo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServicePort_SimulateEntryTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimulateEntryTime'
type MockServicePort_SimulateEntryTime_Call struct {
	*mock.Call
}

// SimulateEntryTime is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - minutesAgo int
func (_e *MockServicePort_Expecter) SimulateEntryTime(ctx interface{}, id interface{}, minutesAgo interface{}) *MockServicePort_SimulateEntryTime_Call {
	return &MockServicePort_SimulateEntryTime_Call{Call: _e.mock.On("SimulateEntryTime", ctx, id, minutesAgo)}
}

func (_c *MockServicePort_SimulateEntryTime_Call) Run(run func(ctx context.Context, id uuid.UUID, minutesAgo int)) *MockServicePort_SimulateEntryTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockServicePort_SimulateEntryTime_Call) Return(_a0 *transaction.Transaction, _a1 error) *MockServicePort_SimulateEntryTime_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServicePort_SimulateEntryTime_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (*transaction.Transaction, error)) *MockServicePort_SimulateEntryTime_Call {
	_c.Call.Return(run)
	return _c
}

// StampPlateMismatch provides a mock function with given fields: ctx, txID, mismatch
func (_m *MockServicePort) StampPlateMismatch(ctx context.Context, txID uuid.UUID, mismatch bool) error {
	ret := _m.Called(ctx, txID, mismatch)

	if len(ret) == 0 {
		panic("no return value specified for StampPlateMismatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, txID, mismatch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServicePort_StampPlateMismatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StampPlateMismatch'
type MockServicePort_StampPlateMismatch_Call struct {
	*mock.Call
}

// StampPlateMismatch is a helper method to define mock.On call
//   - ctx context.Context
//   - txID uuid.UUID
//   - mismatch bool
func (_e *MockServicePort_Expecter) StampPlateMismatch(ctx interface{}, txID interface{}, mismatch interface{}) *MockServicePort_StampPlateMismatch_Call {
	return &MockServicePort_StampPlateMismatch_Call{Call: _e.mock.On("StampPlateMismatch", ctx, txID, mismatch)}
}

func (_c *MockServicePort_StampPlateMismatch_Call) Run(run func(ctx context.Context, txID uuid.UUID, mismatch bool)) *MockServicePort_StampPlateMismatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockServicePort_StampPlateMismatch_Call) Return(_a0 error) *MockServicePort_StampPlateMismatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServicePort_StampPlateMismatch_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockServicePort_StampPlateMismatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServicePort creates a new instance of MockServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicePort {
	mock := &MockServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
