// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	ocr "parkieee/internal/modules/ocr"
	transaction "parkieee/internal/modules/transaction"

	mock "github.com/stretchr/testify/mock"

	types "parkieee/pkg/types"

	uuid "github.com/google/uuid"
)

// MockServicePort is an autogenerated mock type for the ServicePort type
type MockServicePort struct {
	mock.Mock
}

type MockServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicePort) EXPECT() *MockServicePort_Expecter {
	return &MockServicePort_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, id, reason, operatorID
func (_m *MockServicePort) Cancel(ctx context.Context, id uuid.UUID, reason string, operatorID uuid.UUID) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, id, reason, operatorID)
	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}
	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (*transaction.Transaction, error)); ok {
		return rf(ctx, id, reason, operatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) *transaction.Transaction); ok {
		r0 = rf(ctx, id, reason, operatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, id, reason, operatorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockServicePort_Expecter) Cancel(ctx interface{}, id interface{}, reason interface{}, operatorID interface{}) *mock.Call {
	return _e.mock.On("Cancel", ctx, id, reason, operatorID)
}

// GetByCode provides a mock function with given fields: ctx, code
func (_m *MockServicePort) GetByCode(ctx context.Context, code string) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, code)
	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}
	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*transaction.Transaction, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *transaction.Transaction); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockServicePort_Expecter) GetByCode(ctx interface{}, code interface{}) *mock.Call {
	return _e.mock.On("GetByCode", ctx, code)
}

// GetLogs provides a mock function with given fields: ctx, txID
func (_m *MockServicePort) GetLogs(ctx context.Context, txID uuid.UUID) ([]transaction.TransactionLog, error) {
	ret := _m.Called(ctx, txID)
	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}
	var r0 []transaction.TransactionLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]transaction.TransactionLog, error)); ok {
		return rf(ctx, txID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []transaction.TransactionLog); ok {
		r0 = rf(ctx, txID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.TransactionLog)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, txID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockServicePort_Expecter) GetLogs(ctx interface{}, txID interface{}) *mock.Call {
	return _e.mock.On("GetLogs", ctx, txID)
}

// GetOpenByRFIDUID provides a mock function with given fields: ctx, uid
func (_m *MockServicePort) GetOpenByRFIDUID(ctx context.Context, uid string) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, uid)
	if len(ret) == 0 {
		panic("no return value specified for GetOpenByRFIDUID")
	}
	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*transaction.Transaction, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *transaction.Transaction); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockServicePort_Expecter) GetOpenByRFIDUID(ctx interface{}, uid interface{}) *mock.Call {
	return _e.mock.On("GetOpenByRFIDUID", ctx, uid)
}

// GetTransaction provides a mock function with given fields: ctx, id
func (_m *MockServicePort) GetTransaction(ctx context.Context, id uuid.UUID) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, id)
	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}
	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*transaction.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *transaction.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockServicePort_Expecter) GetTransaction(ctx interface{}, id interface{}) *mock.Call {
	return _e.mock.On("GetTransaction", ctx, id)
}

// ListTransactions provides a mock function with given fields: ctx, filter, page, pageSize
func (_m *MockServicePort) ListTransactions(ctx context.Context, filter transaction.ListFilter, page int, pageSize int) ([]transaction.Transaction, int64, error) {
	ret := _m.Called(ctx, filter, page, pageSize)
	if len(ret) == 0 {
		panic("no return value specified for ListTransactions")
	}
	var r0 []transaction.Transaction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, transaction.ListFilter, int, int) ([]transaction.Transaction, int64, error)); ok {
		return rf(ctx, filter, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transaction.ListFilter, int, int) []transaction.Transaction); ok {
		r0 = rf(ctx, filter, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.Transaction)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, transaction.ListFilter, int, int) int64); ok {
		r1 = rf(ctx, filter, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if rf, ok := ret.Get(2).(func(context.Context, transaction.ListFilter, int, int) error); ok {
		r2 = rf(ctx, filter, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

func (_e *MockServicePort_Expecter) ListTransactions(ctx interface{}, filter interface{}, page interface{}, pageSize interface{}) *mock.Call {
	return _e.mock.On("ListTransactions", ctx, filter, page, pageSize)
}

// LoadOCRSummary provides a mock function with given fields: ctx, txID
func (_m *MockServicePort) LoadOCRSummary(ctx context.Context, txID uuid.UUID) []ocr.OCRResultWithJob {
	ret := _m.Called(ctx, txID)
	if len(ret) == 0 {
		panic("no return value specified for LoadOCRSummary")
	}
	var r0 []ocr.OCRResultWithJob
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []ocr.OCRResultWithJob); ok {
		r0 = rf(ctx, txID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ocr.OCRResultWithJob)
		}
	}
	return r0
}

func (_e *MockServicePort_Expecter) LoadOCRSummary(ctx interface{}, txID interface{}) *mock.Call {
	return _e.mock.On("LoadOCRSummary", ctx, txID)
}

// MarkExited provides a mock function with given fields: ctx, txID, triggeredBy
func (_m *MockServicePort) MarkExited(ctx context.Context, txID uuid.UUID, triggeredBy types.TriggeredBy) error {
	ret := _m.Called(ctx, txID, triggeredBy)
	if len(ret) == 0 {
		panic("no return value specified for MarkExited")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.TriggeredBy) error); ok {
		r0 = rf(ctx, txID, triggeredBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockServicePort_Expecter) MarkExited(ctx interface{}, txID interface{}, triggeredBy interface{}) *mock.Call {
	return _e.mock.On("MarkExited", ctx, txID, triggeredBy)
}

// MarkPaid provides a mock function with given fields: ctx, txID, triggeredBy, handledByUserID
func (_m *MockServicePort) MarkPaid(ctx context.Context, txID uuid.UUID, triggeredBy types.TriggeredBy, handledByUserID *uuid.UUID) error {
	ret := _m.Called(ctx, txID, triggeredBy, handledByUserID)
	if len(ret) == 0 {
		panic("no return value specified for MarkPaid")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.TriggeredBy, *uuid.UUID) error); ok {
		r0 = rf(ctx, txID, triggeredBy, handledByUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockServicePort_Expecter) MarkPaid(ctx interface{}, txID interface{}, triggeredBy interface{}, handledByUserID interface{}) *mock.Call {
	return _e.mock.On("MarkPaid", ctx, txID, triggeredBy, handledByUserID)
}

// MarkPaidAndExited provides a mock function with given fields: ctx, txID, triggeredBy, handledByUserID
func (_m *MockServicePort) MarkPaidAndExited(ctx context.Context, txID uuid.UUID, triggeredBy types.TriggeredBy, handledByUserID *uuid.UUID) error {
	ret := _m.Called(ctx, txID, triggeredBy, handledByUserID)
	if len(ret) == 0 {
		panic("no return value specified for MarkPaidAndExited")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.TriggeredBy, *uuid.UUID) error); ok {
		r0 = rf(ctx, txID, triggeredBy, handledByUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockServicePort_Expecter) MarkPaidAndExited(ctx interface{}, txID interface{}, triggeredBy interface{}, handledByUserID interface{}) *mock.Call {
	return _e.mock.On("MarkPaidAndExited", ctx, txID, triggeredBy, handledByUserID)
}

// RecordEntry provides a mock function with given fields: ctx, req, operatorID
func (_m *MockServicePort) RecordEntry(ctx context.Context, req transaction.RecordEntryRequest, operatorID uuid.UUID) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, req, operatorID)
	if len(ret) == 0 {
		panic("no return value specified for RecordEntry")
	}
	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, transaction.RecordEntryRequest, uuid.UUID) (*transaction.Transaction, error)); ok {
		return rf(ctx, req, operatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transaction.RecordEntryRequest, uuid.UUID) *transaction.Transaction); ok {
		r0 = rf(ctx, req, operatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, transaction.RecordEntryRequest, uuid.UUID) error); ok {
		r1 = rf(ctx, req, operatorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockServicePort_Expecter) RecordEntry(ctx interface{}, req interface{}, operatorID interface{}) *mock.Call {
	return _e.mock.On("RecordEntry", ctx, req, operatorID)
}

// RecordExit provides a mock function with given fields: ctx, id, req, operatorID
func (_m *MockServicePort) RecordExit(ctx context.Context, id uuid.UUID, req transaction.RecordExitRequest, operatorID uuid.UUID) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, id, req, operatorID)
	if len(ret) == 0 {
		panic("no return value specified for RecordExit")
	}
	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, transaction.RecordExitRequest, uuid.UUID) (*transaction.Transaction, error)); ok {
		return rf(ctx, id, req, operatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, transaction.RecordExitRequest, uuid.UUID) *transaction.Transaction); ok {
		r0 = rf(ctx, id, req, operatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, transaction.RecordExitRequest, uuid.UUID) error); ok {
		r1 = rf(ctx, id, req, operatorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockServicePort_Expecter) RecordExit(ctx interface{}, id interface{}, req interface{}, operatorID interface{}) *mock.Call {
	return _e.mock.On("RecordExit", ctx, id, req, operatorID)
}

// SimulateEntryTime provides a mock function with given fields: ctx, id, minutesAgo
func (_m *MockServicePort) SimulateEntryTime(ctx context.Context, id uuid.UUID, minutesAgo int) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, id, minutesAgo)
	if len(ret) == 0 {
		panic("no return value specified for SimulateEntryTime")
	}
	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*transaction.Transaction, error)); ok {
		return rf(ctx, id, minutesAgo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *transaction.Transaction); ok {
		r0 = rf(ctx, id, minutesAgo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, id, minutesAgo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_e *MockServicePort_Expecter) SimulateEntryTime(ctx interface{}, id interface{}, minutesAgo interface{}) *mock.Call {
	return _e.mock.On("SimulateEntryTime", ctx, id, minutesAgo)
}

// NotifySim provides a mock function with given fields: event
func (_m *MockServicePort) NotifySim(event transaction.SimEvent) {
	_m.Called(event)
}

func (_e *MockServicePort_Expecter) NotifySim(event interface{}) *mock.Call {
	return _e.mock.On("NotifySim", event)
}

// EnrichTransaction provides a mock function with given fields: ctx, tx, includes
func (_m *MockServicePort) EnrichTransaction(ctx context.Context, tx *transaction.Transaction, includes map[string]bool) *transaction.TransactionEnrichment {
	ret := _m.Called(ctx, tx, includes)
	if len(ret) == 0 {
		panic("no return value specified for EnrichTransaction")
	}
	var r0 *transaction.TransactionEnrichment
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.Transaction, map[string]bool) *transaction.TransactionEnrichment); ok {
		return rf(ctx, tx, includes)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*transaction.TransactionEnrichment)
	}
	return r0
}

func (_e *MockServicePort_Expecter) EnrichTransaction(ctx interface{}, tx interface{}, includes interface{}) *mock.Call {
	return _e.mock.On("EnrichTransaction", ctx, tx, includes)
}

// EnrichTransactionList provides a mock function with given fields: ctx, transactions, includes
func (_m *MockServicePort) EnrichTransactionList(ctx context.Context, transactions []transaction.Transaction, includes map[string]bool) map[uuid.UUID]transaction.TransactionEnrichment {
	ret := _m.Called(ctx, transactions, includes)
	if len(ret) == 0 {
		panic("no return value specified for EnrichTransactionList")
	}
	var r0 map[uuid.UUID]transaction.TransactionEnrichment
	if rf, ok := ret.Get(0).(func(context.Context, []transaction.Transaction, map[string]bool) map[uuid.UUID]transaction.TransactionEnrichment); ok {
		return rf(ctx, transactions, includes)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(map[uuid.UUID]transaction.TransactionEnrichment)
	}
	return r0
}

func (_e *MockServicePort_Expecter) EnrichTransactionList(ctx interface{}, transactions interface{}, includes interface{}) *mock.Call {
	return _e.mock.On("EnrichTransactionList", ctx, transactions, includes)
}

// ListenSim provides a mock function
func (_m *MockServicePort) ListenSim() (<-chan transaction.SimEvent, func()) {
	ret := _m.Called()
	if len(ret) == 0 {
		panic("no return value specified for ListenSim")
	}
	var r0 <-chan transaction.SimEvent
	var r1 func()
	if rf, ok := ret.Get(0).(func() (<-chan transaction.SimEvent, func())); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() <-chan transaction.SimEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan transaction.SimEvent)
		}
	}
	if rf, ok := ret.Get(1).(func() func()); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	return r0, r1
}

func (_e *MockServicePort_Expecter) ListenSim() *mock.Call {
	return _e.mock.On("ListenSim")
}

// StampPlateMismatch provides a mock function with given fields: ctx, txID, mismatch
func (_m *MockServicePort) StampPlateMismatch(ctx context.Context, txID uuid.UUID, mismatch bool) error {
	ret := _m.Called(ctx, txID, mismatch)
	if len(ret) == 0 {
		panic("no return value specified for StampPlateMismatch")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, txID, mismatch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (_e *MockServicePort_Expecter) StampPlateMismatch(ctx interface{}, txID interface{}, mismatch interface{}) *mock.Call {
	return _e.mock.On("StampPlateMismatch", ctx, txID, mismatch)
}

// NewMockServicePort creates a new instance of MockServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicePort {
	mock := &MockServicePort{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
